// grade1_english_bank.dart
// 小小学霸 App - 小学一年级英语题库
// 教材参考：陕西西安人教版PEP英语（一年级上下学期）
// 题目数量：200道四选一选择题
// 适用对象：6-7岁小学一年级学生
// 知识点覆盖：
//   - 字母（26个字母大小写认读、顺序）约30题
//   - 问候与自我介绍（Hello/Hi, Good morning, What's your name, How are you）约25题
//   - 颜色（red, blue, green, yellow, black, white, pink, orange, brown, purple）约20题
//   - 数字1-20（认读、拼写、简单计算）约25题
//   - 身体部位（head, eye, ear, nose, mouth, hand, foot, arm, leg）约20题
//   - 动物（cat, dog, bird, fish, monkey, panda, elephant, tiger, rabbit）约20题
//   - 食物与饮料（apple, banana, cake, milk, water, egg, bread, juice）约20题
//   - 文具（book, pen, pencil, ruler, bag, eraser）约15题
//   - 家庭成员（father, mother, brother, sister, grandfather, grandmother）约15题
//   - 常用指令与简单对话 约10题
//   - 歌谣与韵句 约10题

List<List<dynamic>> grade1EnglishBank = [
  // ========== 字母部分（30题）==========
  ["字母 A 的小写是？", ["d", "a", "c", "b"], "a"],
  ["字母 B 的小写是？", ["d", "c", "b", "a"], "b"],
  ["字母 C 的小写是？", ["f", "e", "d", "c"], "c"],
  ["字母 D 的小写是？", ["d", "e", "c", "b"], "d"],
  ["字母 E 的小写是？", ["e", "f", "g", "d"], "e"],
  ["字母 a 的大写是？", ["D", "B", "C", "A"], "A"],
  ["字母 b 的大写是？", ["A", "B", "C", "D"], "B"],
  ["字母 c 的大写是？", ["B", "A", "D", "C"], "C"],
  ["字母 d 的大写是？", ["D", "B", "A", "C"], "D"],
  ["字母 e 的大写是？", ["E", "G", "D", "F"], "E"],
  ["字母表中，A 后面是？", ["D", "B", "C", "E"], "C"],
  ["字母表中，C 后面是？", ["E", "D", "B", "A"], "D"],
  ["字母表中，E 后面是？", ["F", "H", "G", "D"], "F"],
  ["字母表中，G 后面是？", ["F", "J", "H", "I"], "H"],
  ["字母表中，B 前面是？", ["E", "D", "A", "C"], "A"],
  ["字母表中，D 前面是？", ["A", "E", "C", "B"], "C"],
  ["字母表中，F 前面是？", ["G", "H", "E", "D"], "E"],
  ["字母 H 的小写是？", ["i", "h", "g", "j"], "h"],
  ["字母 i 的大写是？", ["G", "H", "I", "J"], "I"],
  ["字母 M 的小写是？", ["n", "m", "k", "l"], "m"],
  ["字母 n 的大写是？", ["L", "K", "M", "N"], "N"],
  ["字母 O 的小写是？", ["q", "o", "p", "r"], "o"],
  ["字母 P 的小写是？", ["r", "o", "p", "q"], "p"],
  ["字母 Q 的小写是？", ["s", "q", "p", "r"], "q"],
  ["字母 R 的小写是？", ["t", "q", "r", "s"], "r"],
  ["字母 S 的小写是？", ["r", "u", "s", "t"], "s"],
  ["字母 T 的小写是？", ["s", "u", "v", "t"], "t"],
  ["字母表中，J K L 的下一个字母是？", ["K", "L", "N", "M"], "M"],
  ["字母表中，P Q R 的下一个字母是？", ["T", "Q", "R", "S"], "S"],
  ["字母表中，V W X 的下一个字母是？", ["Z", "X", "W", "Y"], "Y"],

  // ========== 问候与自我介绍（25题）==========
  ["早上见到老师，应该说？", ["Goodbye", "Good night", "Hello", "Good morning"], "Good morning"],
  ["Good morning 的中文意思是？", ["晚上好", "早上好", "你好", "再见"], "早上好"],
  ["Hello 的中文意思是？", ["你好", "再见", "谢谢", "对不起"], "你好"],
  ["Hi 的中文意思是？", ["晚安", "再见", "嗨/你好", "谢谢"], "嗨/你好"],
  ["见到朋友打招呼，可以说？", ["Thank you", "Sorry", "Hello", "Goodbye"], "Hello"],
  ["What's your name? 的意思是？", ["你多大了？", "你叫什么名字？", "你在做什么？", "你好吗？"], "你叫什么名字？"],
  ["回答 What's your name? 应该说？", ["Thank you", "Goodbye", "I'm fine", "My name is..."], "My name is..."],
  ["My name is Tom. 的意思是？", ["我是汤姆", "汤姆是我的朋友", "我喜欢汤姆", "我的名字是汤姆"], "我的名字是汤姆"],
  ["How are you? 的意思是？", ["你叫什么名字？", "你多大了？", "你好吗？", "你在哪里？"], "你好吗？"],
  ["回答 How are you? 可以说？", ["Good morning", "My name is...", "I'm fine, thank you", "Goodbye"], "I'm fine, thank you"],
  ["I'm fine, thank you. 的意思是？", ["我很好，谢谢", "谢谢你", "我不太好", "再见"], "我很好，谢谢"],
  ["Goodbye 的中文意思是？", ["再见", "对不起", "谢谢", "你好"], "再见"],
  ["Bye-bye 的中文意思是？", ["晚安", "拜拜/再见", "谢谢", "你好"], "拜拜/再见"],
  ["See you! 的意思是？", ["对不起！", "谢谢你！", "再见！", "你好！"], "再见！"],
  ["放学回家，对同学说？", ["Good morning", "Goodbye", "Thank you", "Hello"], "Goodbye"],
  ["Nice to meet you! 的意思是？", ["早上好！", "很高兴认识你！", "你好吗？", "再见！"], "很高兴认识你！"],
  ["回答 Nice to meet you! 应该说？", ["Thank you", "Nice to meet you, too!", "Hello", "Goodbye"], "Nice to meet you, too!"],
  ["Good afternoon 的中文意思是？", ["下午好", "早上好", "晚上好", "晚安"], "下午好"],
  ["Good night 的中文意思是？", ["晚安", "早上好", "再见", "下午好"], "晚安"],
  ["I'm... 的意思是？", ["你是...", "我是...", "她是...", "他是..."], "我是..."],
  ["自我介绍时说：____ Lucy. 横线处填？", ["She's", "You're", "He's", "I'm"], "I'm"],
  ["对朋友说 Hello! 朋友应该回答？", ["Hello!", "Sorry!", "Goodbye!", "Thank you!"], "Hello!"],
  ["早上见到同学说 Good morning! 你应该回答？", ["Good morning!", "Good night!", "Good afternoon!", "Goodbye!"], "Good morning!"],
  ["How are you? 的礼貌回答是？", ["Go away", "I'm fine, thank you", "No", "I'm not good"], "I'm fine, thank you"],
  ["初次见面，除了 Hello 还可以说？", ["No", "Sorry", "Bye", "Hi"], "Hi"],

  // ========== 颜色（20题）==========
  ["red 的中文意思是？", ["绿色", "红色", "黄色", "蓝色"], "红色"],
  ["blue 的中文意思是？", ["蓝色", "红色", "绿色", "黄色"], "蓝色"],
  ["green 的中文意思是？", ["红色", "蓝色", "绿色", "黄色"], "绿色"],
  ["yellow 的中文意思是？", ["红色", "黄色", "蓝色", "绿色"], "黄色"],
  ["黑色的英文是？", ["black", "white", "red", "blue"], "black"],
  ["白色的英文是？", ["red", "black", "blue", "white"], "white"],
  ["粉色的英文是？", ["orange", "purple", "brown", "pink"], "pink"],
  ["橙色的英文是？", ["brown", "pink", "orange", "purple"], "orange"],
  ["棕色的英文是？", ["brown", "orange", "pink", "purple"], "brown"],
  ["紫色的英文意思是？", ["pink", "orange", "purple", "brown"], "purple"],
  ["苹果通常是 ____ 颜色。", ["green", "black", "blue", "red"], "red"],
  ["天空通常是 ____ 颜色。", ["red", "yellow", "green", "blue"], "blue"],
  ["小草通常是 ____ 颜色。", ["yellow", "blue", "green", "red"], "green"],
  ["香蕉通常是 ____ 颜色。", ["blue", "green", "red", "yellow"], "yellow"],
  ["熊猫的颜色是黑白，黑色是 black，白色是？", ["black", "red", "white", "blue"], "white"],
  ["彩虹有七种颜色，red 是红色，blue 是蓝色，green 是？", ["黄色", "橙色", "绿色", "紫色"], "绿色"],
  ["orange 既是水果橙子，也是颜色？", ["绿色", "红色", "黄色", "橙色"], "橙色"],
  ["red, yellow, ____ 是红绿灯的颜色。", ["white", "green", "black", "blue"], "green"],
  ["black 的中文意思是？", ["黑色", "红色", "蓝色", "白色"], "黑色"],
  ["white 的中文意思是？", ["红色", "蓝色", "白色", "黑色"], "白色"],

  // ========== 数字1-20（25题）==========
  ["one 的中文意思是？", ["二", "四", "一", "三"], "一"],
  ["two 的中文意思是？", ["三", "一", "四", "二"], "二"],
  ["three 的中文意思是？", ["二", "一", "三", "四"], "三"],
  ["four 的中文意思是？", ["一", "二", "三", "四"], "四"],
  ["five 的中文意思是？", ["五", "六", "七", "四"], "五"],
  ["1 的英文是？", ["four", "two", "one", "three"], "one"],
  ["2 的英文是？", ["four", "two", "one", "three"], "two"],
  ["3 的英文是？", ["four", "two", "three", "one"], "three"],
  ["4 的英文是？", ["one", "three", "two", "four"], "four"],
  ["5 的英文是？", ["four", "six", "seven", "five"], "five"],
  ["six 的中文意思是？", ["五", "八", "七", "六"], "六"],
  ["seven 的中文意思是？", ["八", "九", "六", "七"], "七"],
  ["eight 的中文意思是？", ["十", "八", "七", "九"], "八"],
  ["nine 的中文意思是？", ["七", "九", "十", "八"], "九"],
  ["ten 的中文意思是？", ["七", "八", "十", "九"], "十"],
  ["6 的英文是？", ["six", "five", "eight", "seven"], "six"],
  ["7 的英文是？", ["six", "nine", "seven", "eight"], "seven"],
  ["8 的英文是？", ["eight", "ten", "seven", "nine"], "eight"],
  ["9 的英文是？", ["eight", "ten", "seven", "nine"], "nine"],
  ["10 的英文是？", ["eight", "seven", "ten", "nine"], "ten"],
  ["eleven 的中文意思是？", ["十四", "十二", "十三", "十一"], "十一"],
  ["twelve 的中文意思是？", ["十二", "十四", "十三", "十一"], "十二"],
  ["fifteen 的中文意思是？", ["十四", "十六", "十七", "十五"], "十五"],
  ["twenty 的中文意思是？", ["十八", "十五", "十二", "二十"], "二十"],
  ["one + two = ?", ["six", "three", "four", "five"], "three"],

  // ========== 身体部位（20题）==========
  ["head 的中文意思是？", ["头", "脚", "手", "眼睛"], "头"],
  ["eye 的中文意思是？", ["鼻子", "耳朵", "眼睛", "嘴巴"], "眼睛"],
  ["ear 的中文意思是？", ["眼睛", "耳朵", "嘴巴", "鼻子"], "耳朵"],
  ["nose 的中文意思是？", ["嘴巴", "眼睛", "耳朵", "鼻子"], "鼻子"],
  ["mouth 的中文意思是？", ["嘴巴", "鼻子", "眼睛", "耳朵"], "嘴巴"],
  ["hand 的中文意思是？", ["头", "腿", "手", "脚"], "手"],
  ["foot 的中文意思是？", ["手", "脚", "腿", "头"], "脚"],
  ["arm 的中文意思是？", ["脚", "胳膊/手臂", "手", "腿"], "胳膊/手臂"],
  ["leg 的中文意思是？", ["胳膊", "脚", "手", "腿"], "腿"],
  ["头的英文是？", ["hand", "foot", "eye", "head"], "head"],
  ["眼睛的英文是？", ["eye", "nose", "ear", "mouth"], "eye"],
  ["耳朵的英文是？", ["eye", "mouth", "nose", "ear"], "ear"],
  ["鼻子的英文是？", ["nose", "ear", "mouth", "eye"], "nose"],
  ["嘴巴的英文是？", ["ear", "mouth", "nose", "eye"], "mouth"],
  ["手的英文是？", ["hand", "head", "leg", "foot"], "hand"],
  ["脚的英文是？", ["leg", "head", "hand", "foot"], "foot"],
  ["我们用 ____ 看东西。", ["nose", "mouth", "eyes", "ears"], "eyes"],
  ["我们用 ____ 听声音。", ["eyes", "ears", "nose", "mouth"], "ears"],
  ["我们用 ____ 闻气味。", ["ears", "mouth", "eyes", "nose"], "nose"],
  ["我们用 ____ 吃东西。", ["nose", "mouth", "eyes", "ears"], "mouth"],

  // ========== 动物（20题）==========
  ["cat 的中文意思是？", ["猫", "鸟", "狗", "鱼"], "猫"],
  ["dog 的中文意思是？", ["猫", "鱼", "鸟", "狗"], "狗"],
  ["bird 的中文意思是？", ["鸟", "猫", "鱼", "狗"], "鸟"],
  ["fish 的中文意思是？", ["猫", "鸟", "狗", "鱼"], "鱼"],
  ["monkey 的中文意思是？", ["大象", "熊猫", "老虎", "猴子"], "猴子"],
  ["panda 的中文意思是？", ["老虎", "大象", "熊猫", "猴子"], "熊猫"],
  ["elephant 的中文意思是？", ["猴子", "老虎", "熊猫", "大象"], "大象"],
  ["tiger 的中文意思是？", ["大象", "猴子", "熊猫", "老虎"], "老虎"],
  ["rabbit 的中文意思是？", ["狗", "猫", "兔子", "鸟"], "兔子"],
  ["猫的英文是？", ["bird", "dog", "cat", "fish"], "cat"],
  ["狗的英文是？", ["bird", "fish", "dog", "cat"], "dog"],
  ["鸟的英文是？", ["bird", "dog", "fish", "cat"], "bird"],
  ["鱼的英文是？", ["dog", "cat", "bird", "fish"], "fish"],
  ["猴子的英文是？", ["tiger", "elephant", "panda", "monkey"], "monkey"],
  ["熊猫的英文是？", ["elephant", "monkey", "tiger", "panda"], "panda"],
  ["大象的英文是？", ["elephant", "panda", "tiger", "monkey"], "elephant"],
  ["老虎的英文是？", ["tiger", "elephant", "monkey", "panda"], "tiger"],
  ["兔子的英文是？", ["rabbit", "bird", "cat", "dog"], "rabbit"],
  ["会喵喵叫的动物是？", ["fish", "dog", "cat", "bird"], "cat"],
  ["会汪汪叫的动物是？", ["dog", "bird", "fish", "cat"], "dog"],

  // ========== 食物与饮料（20题）==========
  ["apple 的中文意思是？", ["香蕉", "蛋糕", "苹果", "牛奶"], "苹果"],
  ["banana 的中文意思是？", ["牛奶", "苹果", "香蕉", "蛋糕"], "香蕉"],
  ["cake 的中文意思是？", ["牛奶", "苹果", "香蕉", "蛋糕"], "蛋糕"],
  ["milk 的中文意思是？", ["蛋糕", "牛奶", "香蕉", "苹果"], "牛奶"],
  ["water 的中文意思是？", ["水", "茶", "牛奶", "果汁"], "水"],
  ["egg 的中文意思是？", ["鸡蛋", "面包", "牛奶", "蛋糕"], "鸡蛋"],
  ["bread 的中文意思是？", ["蛋糕", "牛奶", "面包", "鸡蛋"], "面包"],
  ["juice 的中文意思是？", ["水", "茶", "果汁", "牛奶"], "果汁"],
  ["苹果的英文是？", ["milk", "cake", "apple", "banana"], "apple"],
  ["香蕉的英文是？", ["apple", "banana", "milk", "cake"], "banana"],
  ["蛋糕的英文是？", ["cake", "banana", "apple", "milk"], "cake"],
  ["牛奶的英文是？", ["milk", "cake", "apple", "banana"], "milk"],
  ["水的英文是？", ["juice", "milk", "tea", "water"], "water"],
  ["鸡蛋的英文是？", ["egg", "cake", "bread", "milk"], "egg"],
  ["面包的英文是？", ["milk", "cake", "bread", "egg"], "bread"],
  ["果汁的英文是？", ["water", "tea", "juice", "milk"], "juice"],
  ["早餐常喝的白色饮品是？", ["water", "milk", "juice", "tea"], "milk"],
  ["猴子最喜欢吃的水果是？", ["orange", "banana", "apple", "grape"], "banana"],
  ["红色的圆形水果是？", ["pear", "banana", "peach", "apple"], "apple"],
  ["口渴时应该喝？", ["water", "bread", "cake", "egg"], "water"],

  // ========== 文具（15题）==========
  ["book 的中文意思是？", ["书", "尺子", "铅笔", "钢笔"], "书"],
  ["pen 的中文意思是？", ["钢笔", "书", "尺子", "铅笔"], "钢笔"],
  ["pencil 的中文意思是？", ["尺子", "铅笔", "书", "钢笔"], "铅笔"],
  ["ruler 的中文意思是？", ["铅笔", "书", "钢笔", "尺子"], "尺子"],
  ["bag 的中文意思是？", ["钢笔", "书包/袋子", "铅笔", "书"], "书包/袋子"],
  ["eraser 的中文意思是？", ["书", "铅笔", "钢笔", "橡皮"], "橡皮"],
  ["书的英文是？", ["ruler", "book", "pencil", "pen"], "book"],
  ["钢笔的英文是？", ["pencil", "book", "ruler", "pen"], "pen"],
  ["铅笔的英文是？", ["pen", "book", "ruler", "pencil"], "pencil"],
  ["尺子的英文是？", ["ruler", "book", "pen", "pencil"], "ruler"],
  ["书包的英文是？", ["book", "pen", "bag", "pencil"], "bag"],
  ["橡皮的英文是？", ["pen", "pencil", "eraser", "book"], "eraser"],
  ["用来写字画画的文具是？", ["ruler", "pencil", "book", "eraser"], "pencil"],
  ["用来测量长度的文具是？", ["eraser", "book", "pen", "ruler"], "ruler"],
  ["写错了可以用 ____ 擦掉。", ["ruler", "eraser", "pen", "pencil"], "eraser"],

  // ========== 家庭成员（15题）==========
  ["father 的中文意思是？", ["爸爸/父亲", "姐姐", "妈妈", "哥哥"], "爸爸/父亲"],
  ["mother 的中文意思是？", ["爸爸", "妈妈/母亲", "姐姐", "哥哥"], "妈妈/母亲"],
  ["brother 的中文意思是？", ["爸爸", "妈妈", "哥哥/弟弟", "姐姐"], "哥哥/弟弟"],
  ["sister 的中文意思是？", ["姐姐/妹妹", "哥哥", "爸爸", "妈妈"], "姐姐/妹妹"],
  ["grandfather 的中文意思是？", ["爸爸", "奶奶", "爷爷/外公", "妈妈"], "爷爷/外公"],
  ["grandmother 的中文意思是？", ["爷爷", "爸爸", "妈妈", "奶奶/外婆"], "奶奶/外婆"],
  ["爸爸的英文是？", ["father", "sister", "mother", "brother"], "father"],
  ["妈妈的英文是？", ["mother", "sister", "father", "brother"], "mother"],
  ["哥哥/弟弟的英文是？", ["brother", "mother", "father", "sister"], "brother"],
  ["姐姐/妹妹的英文是？", ["mother", "father", "sister", "brother"], "sister"],
  ["爷爷/外公的英文是？", ["grandfather", "father", "grandmother", "mother"], "grandfather"],
  ["奶奶/外婆的英文是？", ["father", "grandfather", "grandmother", "mother"], "grandmother"],
  ["爸爸的爸爸是？", ["grandfather", "grandmother", "brother", "father"], "grandfather"],
  ["妈妈的妈妈是？", ["sister", "mother", "grandfather", "grandmother"], "grandmother"],
  ["My father and mother are my ____.", ["students", "parents", "friends", "teachers"], "parents"],

  // ========== 常用指令与简单对话（10题）==========
  ["Stand up 的意思是？", ["起立", "坐下", "过来", "回去"], "起立"],
  ["Sit down 的意思是？", ["回去", "起立", "坐下", "过来"], "坐下"],
  ["Come here 的意思是？", ["起立", "回去", "过来", "坐下"], "过来"],
  ["Go back 的意思是？", ["起立", "坐下", "过来", "回去"], "回去"],
  ["Open your book 的意思是？", ["拿起你的书", "合上你的书", "放下你的书", "打开你的书"], "打开你的书"],
  ["Close your book 的意思是？", ["拿起你的书", "合上你的书", "打开你的书", "放下你的书"], "合上你的书"],
  ["Listen 的意思是？", ["听", "写", "读", "说"], "听"],
  ["Look 的意思是？", ["听", "读", "说", "看"], "看"],
  ["Say it 的意思是？", ["写它", "说出来", "看它", "听它"], "说出来"],
  ["Read after me 的意思是？", ["看着我", "听我说", "跟我读", "写给我"], "跟我读"],

  // ========== 歌谣与韵句（10题）==========
  ["Twinkle, twinkle, little ____.", ["star", "sun", "sky", "moon"], "star"],
  ["Rain, rain, go ____.", ["come", "away", "back", "here"], "away"],
  ["Head, shoulders, knees and ____.", ["feet", "eyes", "hands", "toes"], "toes"],
  ["If you're happy and you know it, clap your ____.", ["hands", "eyes", "feet", "head"], "hands"],
  ["Old MacDonald had a ____.", ["house", "dog", "car", "farm"], "farm"],
  ["The itsy bitsy spider went up the water ____.", ["pipe", "spout", "hole", "wall"], "spout"],
  ["London Bridge is falling ____.", ["away", "down", "up", "back"], "down"],
  ["Row, row, row your ____.", ["boat", "ship", "car", "bike"], "boat"],
  ["Mary had a little ____.", ["lamb", "cat", "dog", "pig"], "lamb"],
  ["Happy birthday to ____.", ["you", "her", "him", "me"], "you"],
];
