// grade1_english_bank.dart
// 小小学霸 App - 小学一年级英语题库
// 教材参考：陕西西安人教版PEP英语（一年级上下学期）
// 题目数量：200道四选一选择题
// 适用对象：6-7岁小学一年级学生
// 知识点覆盖：
//   - 字母（26个字母大小写认读、顺序）约30题
//   - 问候与自我介绍（Hello/Hi, Good morning, What's your name, How are you）约25题
//   - 颜色（red, blue, green, yellow, black, white, pink, orange, brown, purple）约20题
//   - 数字1-20（认读、拼写、简单计算）约25题
//   - 身体部位（head, eye, ear, nose, mouth, hand, foot, arm, leg）约20题
//   - 动物（cat, dog, bird, fish, monkey, panda, elephant, tiger, rabbit）约20题
//   - 食物与饮料（apple, banana, cake, milk, water, egg, bread, juice）约20题
//   - 文具（book, pen, pencil, ruler, bag, eraser）约15题
//   - 家庭成员（father, mother, brother, sister, grandfather, grandmother）约15题
//   - 常用指令与简单对话 约10题
//   - 歌谣与韵句 约10题

List<List<dynamic>> grade1EnglishBank = [
  // ========== 字母部分（30题）==========
  ["字母 A 的小写是？", ["a", "b", "c", "d"], "a"],
  ["字母 B 的小写是？", ["a", "b", "c", "d"], "b"],
  ["字母 C 的小写是？", ["c", "d", "e", "f"], "c"],
  ["字母 D 的小写是？", ["b", "c", "d", "e"], "d"],
  ["字母 E 的小写是？", ["d", "e", "f", "g"], "e"],
  ["字母 a 的大写是？", ["A", "B", "C", "D"], "A"],
  ["字母 b 的大写是？", ["A", "B", "C", "D"], "B"],
  ["字母 c 的大写是？", ["B", "D", "D", "E"], "C"],
  ["字母 d 的大写是？", ["C", "F", "E", "F"], "D"],
  ["字母 e 的大写是？", ["D", "E", "F", "G"], "E"],
  ["字母表中，A 后面是？", ["B", "C", "D", "E"], "C"],
  ["字母表中，C 后面是？", ["B", "F", "E", "F"], "D"],
  ["字母表中，E 后面是？", ["D", "F", "G", "H"], "F"],
  ["字母表中，G 后面是？", ["F", "H", "I", "J"], "H"],
  ["字母表中，B 前面是？", ["A", "C", "D", "E"], "A"],
  ["字母表中，D 前面是？", ["A", "B", "C", "E"], "C"],
  ["字母表中，F 前面是？", ["D", "E", "G", "H"], "E"],
  ["字母 H 的小写是？", ["g", "h", "i", "j"], "h"],
  ["字母 i 的大写是？", ["G", "H", "I", "J"], "I"],
  ["字母 M 的小写是？", ["m", "n", "l", "k"], "m"],
  ["字母 n 的大写是？", ["M", "N", "L", "K"], "N"],
  ["字母 O 的小写是？", ["o", "p", "q", "r"], "o"],
  ["字母 P 的小写是？", ["o", "p", "q", "r"], "p"],
  ["字母 Q 的小写是？", ["p", "q", "r", "s"], "q"],
  ["字母 R 的小写是？", ["q", "r", "s", "t"], "r"],
  ["字母 S 的小写是？", ["r", "s", "t", "u"], "s"],
  ["字母 T 的小写是？", ["s", "t", "u", "v"], "t"],
  ["字母表中，J K L 的下一个字母是？", ["K", "L", "M", "N"], "M"],
  ["字母表中，P Q R 的下一个字母是？", ["Q", "R", "S", "T"], "S"],
  ["字母表中，V W X 的下一个字母是？", ["W", "X", "Y", "Z"], "Y"],

  // ========== 问候与自我介绍（25题）==========
  ["早上见到老师，应该说？", ["Good morning", "Good night", "Goodbye", "Hello"], "Good morning"],
  ["Good morning 的中文意思是？", ["早上好", "晚上好", "再见", "你好"], "早上好"],
  ["Hello 的中文意思是？", ["你好", "再见", "谢谢", "对不起"], "你好"],
  ["Hi 的中文意思是？", ["嗨/你好", "再见", "谢谢", "晚安"], "嗨/你好"],
  ["见到朋友打招呼，可以说？", ["Hello", "Goodbye", "Thank you", "Sorry"], "Hello"],
  ["What's your name? 的意思是？", ["你叫什么名字？", "你好吗？", "你多大了？", "你在做什么？"], "你叫什么名字？"],
  ["回答 What's your name? 应该说？", ["My name is...", "I'm fine", "Thank you", "Goodbye"], "My name is..."],
  ["My name is Tom. 的意思是？", ["我的名字是汤姆", "我是汤姆", "汤姆是我的朋友", "我喜欢汤姆"], "我的名字是汤姆"],
  ["How are you? 的意思是？", ["你好吗？", "你叫什么名字？", "你多大了？", "你在哪里？"], "你好吗？"],
  ["回答 How are you? 可以说？", ["I'm fine, thank you", "My name is...", "Good morning", "Goodbye"], "I'm fine, thank you"],
  ["I'm fine, thank you. 的意思是？", ["我很好，谢谢", "我不太好", "谢谢你", "再见"], "我很好，谢谢"],
  ["Goodbye 的中文意思是？", ["再见", "你好", "谢谢", "对不起"], "再见"],
  ["Bye-bye 的中文意思是？", ["拜拜/再见", "你好", "谢谢", "晚安"], "拜拜/再见"],
  ["See you! 的意思是？", ["再见！", "你好！", "谢谢你！", "对不起！"], "再见！"],
  ["放学回家，对同学说？", ["Goodbye", "Hello", "Good morning", "Thank you"], "Goodbye"],
  ["Nice to meet you! 的意思是？", ["很高兴认识你！", "你好吗？", "再见！", "早上好！"], "很高兴认识你！"],
  ["回答 Nice to meet you! 应该说？", ["Nice to meet you, too!", "Thank you", "Goodbye", "Hello"], "Nice to meet you, too!"],
  ["Good afternoon 的中文意思是？", ["下午好", "早上好", "晚上好", "晚安"], "下午好"],
  ["Good night 的中文意思是？", ["晚安", "早上好", "下午好", "再见"], "晚安"],
  ["I'm... 的意思是？", ["我是...", "你是...", "他是...", "她是..."], "我是..."],
  ["自我介绍时说：____ Lucy. 横线处填？", ["I'm", "You're", "He's", "She's"], "I'm"],
  ["对朋友说 Hello! 朋友应该回答？", ["Hello!", "Goodbye!", "Thank you!", "Sorry!"], "Hello!"],
  ["早上见到同学说 Good morning! 你应该回答？", ["Good morning!", "Good afternoon!", "Good night!", "Goodbye!"], "Good morning!"],
  ["How are you? 的礼貌回答是？", ["I'm fine, thank you", "I'm not good", "Go away", "No"], "I'm fine, thank you"],
  ["初次见面，除了 Hello 还可以说？", ["Hi", "Bye", "Sorry", "No"], "Hi"],

  // ========== 颜色（20题）==========
  ["red 的中文意思是？", ["红色", "蓝色", "绿色", "黄色"], "红色"],
  ["blue 的中文意思是？", ["蓝色", "红色", "绿色", "黄色"], "蓝色"],
  ["green 的中文意思是？", ["绿色", "红色", "蓝色", "黄色"], "绿色"],
  ["yellow 的中文意思是？", ["黄色", "红色", "蓝色", "绿色"], "黄色"],
  ["黑色的英文是？", ["black", "white", "red", "blue"], "black"],
  ["白色的英文是？", ["white", "black", "red", "blue"], "white"],
  ["粉色的英文是？", ["pink", "orange", "brown", "purple"], "pink"],
  ["橙色的英文是？", ["orange", "pink", "brown", "purple"], "orange"],
  ["棕色的英文是？", ["brown", "pink", "orange", "purple"], "brown"],
  ["紫色的英文意思是？", ["purple", "pink", "orange", "brown"], "purple"],
  ["苹果通常是 ____ 颜色。", ["red", "blue", "green", "black"], "red"],
  ["天空通常是 ____ 颜色。", ["blue", "red", "green", "yellow"], "blue"],
  ["小草通常是 ____ 颜色。", ["green", "red", "blue", "yellow"], "green"],
  ["香蕉通常是 ____ 颜色。", ["yellow", "red", "blue", "green"], "yellow"],
  ["熊猫的颜色是黑白，黑色是 black，白色是？", ["white", "black", "red", "blue"], "white"],
  ["彩虹有七种颜色，red 是红色，blue 是蓝色，green 是？", ["绿色", "黄色", "橙色", "紫色"], "绿色"],
  ["orange 既是水果橙子，也是颜色？", ["橙色", "红色", "黄色", "绿色"], "橙色"],
  ["red, yellow, ____ 是红绿灯的颜色。", ["green", "blue", "white", "black"], "green"],
  ["black 的中文意思是？", ["黑色", "白色", "红色", "蓝色"], "黑色"],
  ["white 的中文意思是？", ["白色", "黑色", "红色", "蓝色"], "白色"],

  // ========== 数字1-20（25题）==========
  ["one 的中文意思是？", ["一", "二", "三", "四"], "一"],
  ["two 的中文意思是？", ["二", "一", "三", "四"], "二"],
  ["three 的中文意思是？", ["三", "一", "二", "四"], "三"],
  ["four 的中文意思是？", ["四", "一", "二", "三"], "四"],
  ["five 的中文意思是？", ["五", "四", "六", "七"], "五"],
  ["1 的英文是？", ["one", "two", "three", "four"], "one"],
  ["2 的英文是？", ["two", "one", "three", "four"], "two"],
  ["3 的英文是？", ["three", "one", "two", "four"], "three"],
  ["4 的英文是？", ["four", "one", "two", "three"], "four"],
  ["5 的英文是？", ["five", "four", "six", "seven"], "five"],
  ["six 的中文意思是？", ["六", "五", "七", "八"], "六"],
  ["seven 的中文意思是？", ["七", "六", "八", "九"], "七"],
  ["eight 的中文意思是？", ["八", "七", "九", "十"], "八"],
  ["nine 的中文意思是？", ["九", "八", "十", "七"], "九"],
  ["ten 的中文意思是？", ["十", "九", "八", "七"], "十"],
  ["6 的英文是？", ["six", "five", "seven", "eight"], "six"],
  ["7 的英文是？", ["seven", "six", "eight", "nine"], "seven"],
  ["8 的英文是？", ["eight", "seven", "nine", "ten"], "eight"],
  ["9 的英文是？", ["nine", "eight", "ten", "seven"], "nine"],
  ["10 的英文是？", ["ten", "nine", "eight", "seven"], "ten"],
  ["eleven 的中文意思是？", ["十一", "十二", "十三", "十四"], "十一"],
  ["twelve 的中文意思是？", ["十二", "十一", "十三", "十四"], "十二"],
  ["fifteen 的中文意思是？", ["十五", "十四", "十六", "十七"], "十五"],
  ["twenty 的中文意思是？", ["二十", "十二", "十五", "十八"], "二十"],
  ["one + two = ?", ["three", "four", "five", "six"], "three"],

  // ========== 身体部位（20题）==========
  ["head 的中文意思是？", ["头", "手", "脚", "眼睛"], "头"],
  ["eye 的中文意思是？", ["眼睛", "耳朵", "鼻子", "嘴巴"], "眼睛"],
  ["ear 的中文意思是？", ["耳朵", "眼睛", "鼻子", "嘴巴"], "耳朵"],
  ["nose 的中文意思是？", ["鼻子", "眼睛", "耳朵", "嘴巴"], "鼻子"],
  ["mouth 的中文意思是？", ["嘴巴", "眼睛", "耳朵", "鼻子"], "嘴巴"],
  ["hand 的中文意思是？", ["手", "头", "脚", "腿"], "手"],
  ["foot 的中文意思是？", ["脚", "手", "头", "腿"], "脚"],
  ["arm 的中文意思是？", ["胳膊/手臂", "腿", "手", "脚"], "胳膊/手臂"],
  ["leg 的中文意思是？", ["腿", "胳膊", "手", "脚"], "腿"],
  ["头的英文是？", ["head", "hand", "foot", "eye"], "head"],
  ["眼睛的英文是？", ["eye", "ear", "nose", "mouth"], "eye"],
  ["耳朵的英文是？", ["ear", "eye", "nose", "mouth"], "ear"],
  ["鼻子的英文是？", ["nose", "eye", "ear", "mouth"], "nose"],
  ["嘴巴的英文是？", ["mouth", "eye", "ear", "nose"], "mouth"],
  ["手的英文是？", ["hand", "head", "foot", "leg"], "hand"],
  ["脚的英文是？", ["foot", "hand", "head", "leg"], "foot"],
  ["我们用 ____ 看东西。", ["eyes", "ears", "nose", "mouth"], "eyes"],
  ["我们用 ____ 听声音。", ["ears", "eyes", "nose", "mouth"], "ears"],
  ["我们用 ____ 闻气味。", ["nose", "eyes", "ears", "mouth"], "nose"],
  ["我们用 ____ 吃东西。", ["mouth", "eyes", "ears", "nose"], "mouth"],

  // ========== 动物（20题）==========
  ["cat 的中文意思是？", ["猫", "狗", "鸟", "鱼"], "猫"],
  ["dog 的中文意思是？", ["狗", "猫", "鸟", "鱼"], "狗"],
  ["bird 的中文意思是？", ["鸟", "猫", "狗", "鱼"], "鸟"],
  ["fish 的中文意思是？", ["鱼", "猫", "狗", "鸟"], "鱼"],
  ["monkey 的中文意思是？", ["猴子", "熊猫", "大象", "老虎"], "猴子"],
  ["panda 的中文意思是？", ["熊猫", "猴子", "大象", "老虎"], "熊猫"],
  ["elephant 的中文意思是？", ["大象", "猴子", "熊猫", "老虎"], "大象"],
  ["tiger 的中文意思是？", ["老虎", "猴子", "熊猫", "大象"], "老虎"],
  ["rabbit 的中文意思是？", ["兔子", "猫", "狗", "鸟"], "兔子"],
  ["猫的英文是？", ["cat", "dog", "bird", "fish"], "cat"],
  ["狗的英文是？", ["dog", "cat", "bird", "fish"], "dog"],
  ["鸟的英文是？", ["bird", "cat", "dog", "fish"], "bird"],
  ["鱼的英文是？", ["fish", "cat", "dog", "bird"], "fish"],
  ["猴子的英文是？", ["monkey", "panda", "elephant", "tiger"], "monkey"],
  ["熊猫的英文是？", ["panda", "monkey", "elephant", "tiger"], "panda"],
  ["大象的英文是？", ["elephant", "monkey", "panda", "tiger"], "elephant"],
  ["老虎的英文是？", ["tiger", "monkey", "panda", "elephant"], "tiger"],
  ["兔子的英文是？", ["rabbit", "cat", "dog", "bird"], "rabbit"],
  ["会喵喵叫的动物是？", ["cat", "dog", "bird", "fish"], "cat"],
  ["会汪汪叫的动物是？", ["dog", "cat", "bird", "fish"], "dog"],

  // ========== 食物与饮料（20题）==========
  ["apple 的中文意思是？", ["苹果", "香蕉", "蛋糕", "牛奶"], "苹果"],
  ["banana 的中文意思是？", ["香蕉", "苹果", "蛋糕", "牛奶"], "香蕉"],
  ["cake 的中文意思是？", ["蛋糕", "苹果", "香蕉", "牛奶"], "蛋糕"],
  ["milk 的中文意思是？", ["牛奶", "苹果", "香蕉", "蛋糕"], "牛奶"],
  ["water 的中文意思是？", ["水", "牛奶", "果汁", "茶"], "水"],
  ["egg 的中文意思是？", ["鸡蛋", "面包", "蛋糕", "牛奶"], "鸡蛋"],
  ["bread 的中文意思是？", ["面包", "鸡蛋", "蛋糕", "牛奶"], "面包"],
  ["juice 的中文意思是？", ["果汁", "牛奶", "水", "茶"], "果汁"],
  ["苹果的英文是？", ["apple", "banana", "cake", "milk"], "apple"],
  ["香蕉的英文是？", ["banana", "apple", "cake", "milk"], "banana"],
  ["蛋糕的英文是？", ["cake", "apple", "banana", "milk"], "cake"],
  ["牛奶的英文是？", ["milk", "apple", "banana", "cake"], "milk"],
  ["水的英文是？", ["water", "milk", "juice", "tea"], "water"],
  ["鸡蛋的英文是？", ["egg", "bread", "cake", "milk"], "egg"],
  ["面包的英文是？", ["bread", "egg", "cake", "milk"], "bread"],
  ["果汁的英文是？", ["juice", "milk", "water", "tea"], "juice"],
  ["早餐常喝的白色饮品是？", ["milk", "water", "juice", "tea"], "milk"],
  ["猴子最喜欢吃的水果是？", ["banana", "apple", "orange", "grape"], "banana"],
  ["红色的圆形水果是？", ["apple", "banana", "pear", "peach"], "apple"],
  ["口渴时应该喝？", ["water", "cake", "bread", "egg"], "water"],

  // ========== 文具（15题）==========
  ["book 的中文意思是？", ["书", "钢笔", "铅笔", "尺子"], "书"],
  ["pen 的中文意思是？", ["钢笔", "书", "铅笔", "尺子"], "钢笔"],
  ["pencil 的中文意思是？", ["铅笔", "书", "钢笔", "尺子"], "铅笔"],
  ["ruler 的中文意思是？", ["尺子", "书", "钢笔", "铅笔"], "尺子"],
  ["bag 的中文意思是？", ["书包/袋子", "书", "钢笔", "铅笔"], "书包/袋子"],
  ["eraser 的中文意思是？", ["橡皮", "书", "钢笔", "铅笔"], "橡皮"],
  ["书的英文是？", ["book", "pen", "pencil", "ruler"], "book"],
  ["钢笔的英文是？", ["pen", "book", "pencil", "ruler"], "pen"],
  ["铅笔的英文是？", ["pencil", "book", "pen", "ruler"], "pencil"],
  ["尺子的英文是？", ["ruler", "book", "pen", "pencil"], "ruler"],
  ["书包的英文是？", ["bag", "book", "pen", "pencil"], "bag"],
  ["橡皮的英文是？", ["eraser", "book", "pen", "pencil"], "eraser"],
  ["用来写字画画的文具是？", ["pencil", "book", "ruler", "eraser"], "pencil"],
  ["用来测量长度的文具是？", ["ruler", "book", "pen", "eraser"], "ruler"],
  ["写错了可以用 ____ 擦掉。", ["eraser", "pen", "pencil", "ruler"], "eraser"],

  // ========== 家庭成员（15题）==========
  ["father 的中文意思是？", ["爸爸/父亲", "妈妈", "哥哥", "姐姐"], "爸爸/父亲"],
  ["mother 的中文意思是？", ["妈妈/母亲", "爸爸", "哥哥", "姐姐"], "妈妈/母亲"],
  ["brother 的中文意思是？", ["哥哥/弟弟", "爸爸", "妈妈", "姐姐"], "哥哥/弟弟"],
  ["sister 的中文意思是？", ["姐姐/妹妹", "爸爸", "妈妈", "哥哥"], "姐姐/妹妹"],
  ["grandfather 的中文意思是？", ["爷爷/外公", "奶奶", "爸爸", "妈妈"], "爷爷/外公"],
  ["grandmother 的中文意思是？", ["奶奶/外婆", "爷爷", "爸爸", "妈妈"], "奶奶/外婆"],
  ["爸爸的英文是？", ["father", "mother", "brother", "sister"], "father"],
  ["妈妈的英文是？", ["mother", "father", "brother", "sister"], "mother"],
  ["哥哥/弟弟的英文是？", ["brother", "father", "mother", "sister"], "brother"],
  ["姐姐/妹妹的英文是？", ["sister", "father", "mother", "brother"], "sister"],
  ["爷爷/外公的英文是？", ["grandfather", "grandmother", "father", "mother"], "grandfather"],
  ["奶奶/外婆的英文是？", ["grandmother", "grandfather", "father", "mother"], "grandmother"],
  ["爸爸的爸爸是？", ["grandfather", "grandmother", "father", "brother"], "grandfather"],
  ["妈妈的妈妈是？", ["grandmother", "grandfather", "mother", "sister"], "grandmother"],
  ["My father and mother are my ____.", ["parents", "friends", "teachers", "students"], "parents"],

  // ========== 常用指令与简单对话（10题）==========
  ["Stand up 的意思是？", ["起立", "坐下", "过来", "回去"], "起立"],
  ["Sit down 的意思是？", ["坐下", "起立", "过来", "回去"], "坐下"],
  ["Come here 的意思是？", ["过来", "起立", "坐下", "回去"], "过来"],
  ["Go back 的意思是？", ["回去", "起立", "坐下", "过来"], "回去"],
  ["Open your book 的意思是？", ["打开你的书", "合上你的书", "拿起你的书", "放下你的书"], "打开你的书"],
  ["Close your book 的意思是？", ["合上你的书", "打开你的书", "拿起你的书", "放下你的书"], "合上你的书"],
  ["Listen 的意思是？", ["听", "说", "读", "写"], "听"],
  ["Look 的意思是？", ["看", "听", "说", "读"], "看"],
  ["Say it 的意思是？", ["说出来", "听它", "看它", "写它"], "说出来"],
  ["Read after me 的意思是？", ["跟我读", "听我说", "看着我", "写给我"], "跟我读"],

  // ========== 歌谣与韵句（10题）==========
  ["Twinkle, twinkle, little ____.", ["star", "moon", "sun", "sky"], "star"],
  ["Rain, rain, go ____.", ["away", "come", "here", "back"], "away"],
  ["Head, shoulders, knees and ____.", ["toes", "hands", "feet", "eyes"], "toes"],
  ["If you're happy and you know it, clap your ____.", ["hands", "feet", "head", "eyes"], "hands"],
  ["Old MacDonald had a ____.", ["farm", "house", "car", "dog"], "farm"],
  ["The itsy bitsy spider went up the water ____.", ["spout", "pipe", "hole", "wall"], "spout"],
  ["London Bridge is falling ____.", ["down", "up", "away", "back"], "down"],
  ["Row, row, row your ____.", ["boat", "ship", "car", "bike"], "boat"],
  ["Mary had a little ____.", ["lamb", "cat", "dog", "pig"], "lamb"],
  ["Happy birthday to ____.", ["you", "me", "him", "her"], "you"],
];
