// 小学二年级英语题库（陕西西安人教版PEP）
// 共200道四选一选择题

final List<List<dynamic>> grade2EnglishBank = [
  // ===== 字母复习（约20题）=====
  ["字母表中第1个字母是什么？", ["A", "B", "C", "D"], "A"],
  ["字母表中第26个字母是什么？", ["X", "Y", "Z", "W"], "Z"],
  ["字母B的左邻右舍是哪两个字母？", ["A和C", "B和D", "C和E", "A和D"], "A和C"],
  ["字母M后面是哪个字母？", ["L", "N", "O", "K"], "N"],
  ["字母P前面是哪个字母？", ["Q", "R", "O", "S"], "O"],
  ["大写字母H的小写形式是什么？", ["h", "n", "m", "l"], "h"],
  ["小写字母d的大写形式是什么？", ["B", "D", "P", "Q"], "D"],
  ["哪个字母在字母表中排第5位？", ["D", "E", "F", "G"], "E"],
  ["哪个字母在字母表中排第10位？", ["H", "I", "J", "K"], "J"],
  ["字母O的左邻右舍是哪两个字母？", ["M和N", "N和P", "P和Q", "L和M"], "N和P"],
  ["字母S后面是哪个字母？", ["R", "T", "U", "V"], "T"],
  ["字母W前面是哪个字母？", ["X", "V", "U", "Y"], "V"],
  ["大写字母Q的小写形式是什么？", ["p", "q", "d", "b"], "q"],
  ["小写字母b的大写形式是什么？", ["D", "P", "B", "R"], "B"],
  ["哪个字母在字母表中排第15位？", ["M", "N", "O", "P"], "O"],
  ["哪个字母在字母表中排第20位？", ["R", "S", "T", "U"], "T"],
  ["字母K的左邻右舍是哪两个字母？", ["I和J", "J和L", "L和M", "H和I"], "J和L"],
  ["字母F后面是哪个字母？", ["E", "G", "H", "D"], "G"],
  ["字母X前面是哪个字母？", ["Y", "Z", "W", "V"], "W"],
  ["哪个字母在字母表中排第7位？", ["F", "G", "H", "I"], "G"],

  // ===== 问候与日常交际（约25题）=====
  ["早上见到老师应该说：", ["Good morning", "Good afternoon", "Good evening", "Good night"], "Good morning"],
  ["下午见到同学应该说：", ["Good morning", "Good afternoon", "Good evening", "Good night"], "Good afternoon"],
  ["晚上睡觉前应该说：", ["Good morning", "Good afternoon", "Good evening", "Good night"], "Good night"],
  ["别人问\"How are you?\"，你应该回答：", ["I'm fine, thank you", "How are you", "Goodbye", "Nice to meet you"], "I'm fine, thank you"],
  ["初次见面应该说：", ["Goodbye", "Nice to meet you", "How are you", "Good morning"], "Nice to meet you"],
  ["和别人告别应该说：", ["Hello", "Goodbye", "How are you", "Nice to meet you"], "Goodbye"],
  ["早上好的英语怎么说？", ["Good morning", "Good afternoon", "Good evening", "Good night"], "Good morning"],
  ["下午好的英语怎么说？", ["Good morning", "Good afternoon", "Good evening", "Good night"], "Good afternoon"],
  ["晚上好的英语怎么说？", ["Good morning", "Good afternoon", "Good evening", "Good night"], "Good evening"],
  ["晚安的英语怎么说？", ["Good morning", "Good afternoon", "Good evening", "Good night"], "Good night"],
  ["你好吗？的英语怎么说？", ["Hello", "How are you", "Goodbye", "Good morning"], "How are you"],
  ["我很好，谢谢的英语怎么说？", ["I'm fine, thank you", "How are you", "Goodbye", "Hello"], "I'm fine, thank you"],
  ["很高兴见到你的英语怎么说？", ["Goodbye", "Nice to meet you", "Hello", "How are you"], "Nice to meet you"],
  ["见到朋友时可以说：", ["Hello", "Goodbye", "Good night", "Good evening"], "Hello"],
  ["\"Thank you\"是什么意思？", ["你好", "谢谢", "再见", "对不起"], "谢谢"],
  ["\"Sorry\"是什么意思？", ["你好", "谢谢", "再见", "对不起"], "对不起"],
  ["别人说\"Thank you\"，你应该说：", ["Sorry", "You're welcome", "Goodbye", "Hello"], "You're welcome"],
  ["\"Please\"是什么意思？", ["请", "谢谢", "对不起", "再见"], "请"],
  ["想请求帮助时应该说：", ["Please help me", "Goodbye", "Good morning", "How are you"], "Please help me"],
  ["别人帮助了你，你应该说：", ["Sorry", "Thank you", "Goodbye", "Hello"], "Thank you"],
  ["早上见面打招呼说：", ["Good morning", "Good afternoon", "Good evening", "Good night"], "Good morning"],
  ["下午三点见面打招呼说：", ["Good morning", "Good afternoon", "Good evening", "Good night"], "Good afternoon"],
  ["晚上七点见面打招呼说：", ["Good morning", "Good afternoon", "Good evening", "Good night"], "Good evening"],
  ["睡觉前对爸爸妈妈说：", ["Good morning", "Good afternoon", "Good evening", "Good night"], "Good night"],
  ["\"Excuse me\"是什么意思？", ["打扰一下", "谢谢", "再见", "你好"], "打扰一下"],

  // ===== 颜色（约15题）=====
  ["红色的英语怎么说？", ["blue", "red", "green", "yellow"], "red"],
  ["蓝色的英语怎么说？", ["blue", "red", "green", "yellow"], "blue"],
  ["黄色的英语怎么说？", ["blue", "red", "green", "yellow"], "yellow"],
  ["绿色的英语怎么说？", ["blue", "red", "green", "yellow"], "green"],
  ["紫色的英语怎么说？", ["pink", "purple", "orange", "brown"], "purple"],
  ["粉色的英语怎么说？", ["pink", "purple", "orange", "brown"], "pink"],
  ["橙色的英语怎么说？", ["pink", "purple", "orange", "brown"], "orange"],
  ["棕色的英语怎么说？", ["pink", "purple", "orange", "brown"], "brown"],
  ["黑色的英语怎么说？", ["white", "black", "gray", "brown"], "black"],
  ["白色的英语怎么说？", ["white", "black", "gray", "brown"], "white"],
  ["灰色的英语怎么说？", ["white", "black", "gray", "brown"], "gray"],
  ["天空是什么颜色？", ["blue", "red", "green", "yellow"], "blue"],
  ["草地是什么颜色？", ["blue", "red", "green", "yellow"], "green"],
  ["香蕉是什么颜色？", ["blue", "red", "green", "yellow"], "yellow"],
  ["熊猫是什么颜色？", ["white and black", "brown", "pink", "orange"], "white and black"],

  // ===== 数字1-100（约25题）=====
  ["数字1的英语怎么说？", ["one", "two", "three", "four"], "one"],
  ["数字5的英语怎么说？", ["three", "four", "five", "six"], "five"],
  ["数字10的英语怎么说？", ["eight", "nine", "ten", "eleven"], "ten"],
  ["数字11的英语怎么说？", ["ten", "eleven", "twelve", "thirteen"], "eleven"],
  ["数字12的英语怎么说？", ["ten", "eleven", "twelve", "thirteen"], "twelve"],
  ["数字15的英语怎么说？", ["thirteen", "fourteen", "fifteen", "sixteen"], "fifteen"],
  ["数字20的英语怎么说？", ["twenty", "thirty", "forty", "fifty"], "twenty"],
  ["数字30的英语怎么说？", ["twenty", "thirty", "forty", "fifty"], "thirty"],
  ["数字40的英语怎么说？", ["twenty", "thirty", "forty", "fifty"], "forty"],
  ["数字50的英语怎么说？", ["twenty", "thirty", "forty", "fifty"], "fifty"],
  ["数字13的英语怎么说？", ["thirteen", "fourteen", "fifteen", "sixteen"], "thirteen"],
  ["数字14的英语怎么说？", ["thirteen", "fourteen", "fifteen", "sixteen"], "fourteen"],
  ["数字16的英语怎么说？", ["fourteen", "fifteen", "sixteen", "seventeen"], "sixteen"],
  ["数字17的英语怎么说？", ["fifteen", "sixteen", "seventeen", "eighteen"], "seventeen"],
  ["数字18的英语怎么说？", ["sixteen", "seventeen", "eighteen", "nineteen"], "eighteen"],
  ["数字19的英语怎么说？", ["seventeen", "eighteen", "nineteen", "twenty"], "nineteen"],
  ["数字60的英语怎么说？", ["fifty", "sixty", "seventy", "eighty"], "sixty"],
  ["数字70的英语怎么说？", ["sixty", "seventy", "eighty", "ninety"], "seventy"],
  ["数字80的英语怎么说？", ["seventy", "eighty", "ninety", "one hundred"], "eighty"],
  ["数字90的英语怎么说？", ["eighty", "ninety", "one hundred", "seventy"], "ninety"],
  ["数字100的英语怎么说？", ["ninety", "one hundred", "ninety-nine", "eighty"], "one hundred"],
  ["21的英语怎么说？", ["twenty-one", "twenty-two", "twenty-three", "twenty-four"], "twenty-one"],
  ["35的英语怎么说？", ["thirty-four", "thirty-five", "thirty-six", "thirty-seven"], "thirty-five"],
  ["42的英语怎么说？", ["forty-one", "forty-two", "forty-three", "forty-four"], "forty-two"],
  ["58的英语怎么说？", ["fifty-six", "fifty-seven", "fifty-eight", "fifty-nine"], "fifty-eight"],

  // ===== 身体部位（约15题）=====
  ["眼睛的英语怎么说？", ["eye", "ear", "nose", "mouth"], "eye"],
  ["耳朵的英语怎么说？", ["eye", "ear", "nose", "mouth"], "ear"],
  ["鼻子的英语怎么说？", ["eye", "ear", "nose", "mouth"], "nose"],
  ["嘴巴的英语怎么说？", ["eye", "ear", "nose", "mouth"], "mouth"],
  ["手的英语怎么说？", ["hand", "foot", "head", "arm"], "hand"],
  ["脚的英语怎么说？", ["hand", "foot", "head", "arm"], "foot"],
  ["头的英语怎么说？", ["hand", "foot", "head", "arm"], "head"],
  ["手臂的英语怎么说？", ["hand", "foot", "head", "arm"], "arm"],
  ["腿的英语怎么说？", ["leg", "arm", "hand", "foot"], "leg"],
  ["手指的英语怎么说？", ["finger", "toe", "shoulder", "knee"], "finger"],
  ["脚趾的英语怎么说？", ["finger", "toe", "shoulder", "knee"], "toe"],
  ["肩膀的英语怎么说？", ["finger", "toe", "shoulder", "knee"], "shoulder"],
  ["膝盖的英语怎么说？", ["finger", "toe", "shoulder", "knee"], "knee"],
  ["脸的英语怎么说？", ["face", "head", "hand", "arm"], "face"],
  ["头发的英语怎么说？", ["hair", "face", "head", "eye"], "hair"],

  // ===== 动物（约20题）=====
  ["狗的英语怎么说？", ["cat", "dog", "bird", "fish"], "dog"],
  ["猫的英语怎么说？", ["cat", "dog", "bird", "fish"], "cat"],
  ["鸟的英语怎么说？", ["cat", "dog", "bird", "fish"], "bird"],
  ["鱼的英语怎么说？", ["cat", "dog", "bird", "fish"], "fish"],
  ["鸭子的英语怎么说？", ["duck", "pig", "cow", "sheep"], "duck"],
  ["猪的英语怎么说？", ["duck", "pig", "cow", "sheep"], "pig"],
  ["奶牛的英语怎么说？", ["duck", "pig", "cow", "sheep"], "cow"],
  ["绵羊的英语怎么说？", ["duck", "pig", "cow", "sheep"], "sheep"],
  ["马的英语怎么说？", ["horse", "bear", "monkey", "panda"], "horse"],
  ["熊的英语怎么说？", ["horse", "bear", "monkey", "panda"], "bear"],
  ["猴子的英语怎么说？", ["horse", "bear", "monkey", "panda"], "monkey"],
  ["熊猫的英语怎么说？", ["horse", "bear", "monkey", "panda"], "panda"],
  ["兔子的英语怎么说？", ["rabbit", "tiger", "lion", "elephant"], "rabbit"],
  ["老虎的英语怎么说？", ["rabbit", "tiger", "lion", "elephant"], "tiger"],
  ["狮子的英语怎么说？", ["rabbit", "tiger", "lion", "elephant"], "lion"],
  ["大象的英语怎么说？", ["rabbit", "tiger", "lion", "elephant"], "elephant"],
  ["鸡的英语怎么说？", ["chicken", "duck", "goose", "bird"], "chicken"],
  ["蛇的英语怎么说？", ["snake", "frog", "turtle", "fish"], "snake"],
  ["青蛙的英语怎么说？", ["snake", "frog", "turtle", "fish"], "frog"],
  ["乌龟的英语怎么说？", ["snake", "frog", "turtle", "fish"], "turtle"],

  // ===== 食物与饮料（约20题）=====
  ["米饭的英语怎么说？", ["rice", "noodle", "bread", "cake"], "rice"],
  ["面条的英语怎么说？", ["rice", "noodle", "bread", "cake"], "noodle"],
  ["面包的英语怎么说？", ["rice", "noodle", "bread", "cake"], "bread"],
  ["蛋糕的英语怎么说？", ["rice", "noodle", "bread", "cake"], "cake"],
  ["鱼的英语（食物）怎么说？", ["fish", "chicken", "beef", "pork"], "fish"],
  ["鸡肉的英语怎么说？", ["fish", "chicken", "beef", "pork"], "chicken"],
  ["牛肉的英语怎么说？", ["fish", "chicken", "beef", "pork"], "beef"],
  ["猪肉的英语怎么说？", ["fish", "chicken", "beef", "pork"], "pork"],
  ["果汁的英语怎么说？", ["juice", "milk", "water", "tea"], "juice"],
  ["牛奶的英语怎么说？", ["juice", "milk", "water", "tea"], "milk"],
  ["水的英语怎么说？", ["juice", "milk", "water", "tea"], "water"],
  ["茶的英语怎么说？", ["juice", "milk", "water", "tea"], "tea"],
  ["苹果的英语怎么说？", ["apple", "banana", "orange", "pear"], "apple"],
  ["香蕉的英语怎么说？", ["apple", "banana", "orange", "pear"], "banana"],
  ["橙子的英语怎么说？", ["apple", "banana", "orange", "pear"], "orange"],
  ["梨的英语怎么说？", ["apple", "banana", "orange", "pear"], "pear"],
  ["鸡蛋的英语怎么说？", ["egg", "apple", "cake", "bread"], "egg"],
  ["蔬菜的英语怎么说？", ["vegetable", "fruit", "meat", "rice"], "vegetable"],
  ["水果的英语怎么说？", ["vegetable", "fruit", "meat", "rice"], "fruit"],
  ["冰淇淋的英语怎么说？", ["ice cream", "cake", "bread", "cookie"], "ice cream"],

  // ===== 衣服（约15题）=====
  ["衬衫的英语怎么说？", ["shirt", "T-shirt", "skirt", "dress"], "shirt"],
  ["T恤的英语怎么说？", ["shirt", "T-shirt", "skirt", "dress"], "T-shirt"],
  ["裙子的英语怎么说？", ["shirt", "T-shirt", "skirt", "dress"], "skirt"],
  ["连衣裙的英语怎么说？", ["shirt", "T-shirt", "skirt", "dress"], "dress"],
  ["帽子的英语怎么说？", ["hat", "cap", "shoes", "socks"], "hat"],
  ["鞋子的英语怎么说？", ["hat", "cap", "shoes", "socks"], "shoes"],
  ["袜子的英语怎么说？", ["hat", "cap", "shoes", "socks"], "socks"],
  ["裤子的英语怎么说？", ["pants", "shorts", "coat", "jacket"], "pants"],
  ["短裤的英语怎么说？", ["pants", "shorts", "coat", "jacket"], "shorts"],
  ["外套的英语怎么说？", ["pants", "shorts", "coat", "jacket"], "coat"],
  ["夹克的英语怎么说？", ["pants", "shorts", "coat", "jacket"], "jacket"],
  ["毛衣的英语怎么说？", ["sweater", "coat", "jacket", "shirt"], "sweater"],
  ["手套的英语怎么说？", ["gloves", "socks", "shoes", "hat"], "gloves"],
  ["围巾的英语怎么说？", ["scarf", "hat", "gloves", "coat"], "scarf"],
  ["雨衣的英语怎么说？", ["raincoat", "coat", "jacket", "sweater"], "raincoat"],

  // ===== 交通工具（约15题）=====
  ["小汽车的英语怎么说？", ["car", "bus", "bike", "train"], "car"],
  ["公共汽车的英语怎么说？", ["car", "bus", "bike", "train"], "bus"],
  ["自行车的英语怎么说？", ["car", "bus", "bike", "train"], "bike"],
  ["火车的英语怎么说？", ["car", "bus", "bike", "train"], "train"],
  ["飞机的英语怎么说？", ["plane", "ship", "boat", "car"], "plane"],
  ["轮船的英语怎么说？", ["plane", "ship", "boat", "car"], "ship"],
  ["小船的英语怎么说？", ["plane", "ship", "boat", "car"], "boat"],
  ["出租车的英语怎么说？", ["taxi", "bus", "car", "train"], "taxi"],
  ["地铁的英语怎么说？", ["subway", "train", "bus", "taxi"], "subway"],
  ["摩托车的英语怎么说？", ["motorcycle", "bike", "car", "bus"], "motorcycle"],
  ["直升机/直升飞机的英语怎么说？", ["helicopter", "plane", "ship", "train"], "helicopter"],
  ["卡车/货车的英语怎么说？", ["truck", "car", "bus", "taxi"], "truck"],
  ["警车的英语怎么说？", ["police car", "bus", "taxi", "truck"], "police car"],
  ["救护车的英语怎么说？", ["ambulance", "police car", "fire truck", "bus"], "ambulance"],
  ["消防车的英语怎么说？", ["ambulance", "police car", "fire truck", "bus"], "fire truck"],

  // ===== 星期与月份（约15题）=====
  ["星期一的英语怎么说？", ["Monday", "Tuesday", "Wednesday", "Thursday"], "Monday"],
  ["星期二的英语怎么说？", ["Monday", "Tuesday", "Wednesday", "Thursday"], "Tuesday"],
  ["星期三的英语怎么说？", ["Monday", "Tuesday", "Wednesday", "Thursday"], "Wednesday"],
  ["星期四的英语怎么说？", ["Monday", "Tuesday", "Wednesday", "Thursday"], "Thursday"],
  ["星期五的英语怎么说？", ["Friday", "Saturday", "Sunday", "Monday"], "Friday"],
  ["星期六的英语怎么说？", ["Friday", "Saturday", "Sunday", "Monday"], "Saturday"],
  ["星期日的英语怎么说？", ["Friday", "Saturday", "Sunday", "Monday"], "Sunday"],
  ["一月的英语怎么说？", ["January", "February", "March", "April"], "January"],
  ["二月的英语怎么说？", ["January", "February", "March", "April"], "February"],
  ["三月的英语怎么说？", ["January", "February", "March", "April"], "March"],
  ["四月的英语怎么说？", ["January", "February", "March", "April"], "April"],
  ["五月的英语怎么说？", ["May", "June", "July", "August"], "May"],
  ["六月的英语怎么说？", ["May", "June", "July", "August"], "June"],
  ["七月的英语怎么说？", ["May", "June", "July", "August"], "July"],
  ["八月的英语怎么说？", ["May", "June", "July", "August"], "August"],

  // ===== 简单句型（约15题）=====
  ["\"我喜欢苹果\"用英语怎么说？", ["I like apples", "I have apples", "This is an apple", "I see apples"], "I like apples"],
  ["\"我有一只猫\"用英语怎么说？", ["I like a cat", "I have a cat", "This is a cat", "I see a cat"], "I have a cat"],
  ["\"这是一本书\"用英语怎么说？", ["I like a book", "I have a book", "This is a book", "I see a book"], "This is a book"],
  ["\"这是什么颜色？\"用英语怎么说？", ["What colour is it", "What is it", "How many", "Where is it"], "What colour is it"],
  ["\"有多少个苹果？\"用英语怎么说？", ["What colour", "How many apples", "What is it", "Where is it"], "How many apples"],
  ["\"它是红色的\"用英语怎么说？", ["It's red", "It's blue", "It's green", "It's yellow"], "It's red"],
  ["\"我喜欢狗\"用英语怎么说？", ["I like dogs", "I have dogs", "This is a dog", "I see dogs"], "I like dogs"],
  ["\"我有一本书\"用英语怎么说？", ["I like a book", "I have a book", "This is a book", "I see a book"], "I have a book"],
  ["\"这是一只猫\"用英语怎么说？", ["I like a cat", "I have a cat", "This is a cat", "I see a cat"], "This is a cat"],
  ["\"它是蓝色的\"用英语怎么说？", ["It's red", "It's blue", "It's green", "It's yellow"], "It's blue"],
  ["\"我喜欢香蕉\"用英语怎么说？", ["I like bananas", "I have bananas", "This is a banana", "I see bananas"], "I like bananas"],
  ["\"我有两只手\"用英语怎么说？", ["I like two hands", "I have two hands", "This is a hand", "I see two hands"], "I have two hands"],
  ["\"这是什么？\"用英语怎么说？", ["What colour", "What is this", "How many", "Where is it"], "What is this"],
  ["\"它在哪儿？\"用英语怎么说？", ["What colour", "What is this", "How many", "Where is it"], "Where is it"],
  ["\"它是绿色的\"用英语怎么说？", ["It's red", "It's blue", "It's green", "It's yellow"], "It's green"],

  // ===== 补充题目（5题）=====
  ["\"再见\"的英语怎么说？", ["Goodbye", "Hello", "Sorry", "Thank you"], "Goodbye"],
  ["九月的英语怎么说？", ["September", "October", "November", "December"], "September"],
  ["十月的英语怎么说？", ["September", "October", "November", "December"], "October"],
  ["十一月的英语怎么说？", ["September", "October", "November", "December"], "November"],
  ["十二月的英语怎么说？", ["September", "October", "November", "December"], "December"],
];
