// 小学二年级英语题库（陕西西安人教版PEP）
// 共200道四选一选择题

final List<List<dynamic>> grade2EnglishBank = [
  // ===== 字母复习（约20题）=====
  ["字母表中第1个字母是什么？", ["B", "C", "D", "A"], "A"],
  ["字母表中第26个字母是什么？", ["Z", "X", "Y", "W"], "Z"],
  ["字母B的左邻右舍是哪两个字母？", ["A和D", "C和E", "A和C", "B和D"], "A和C"],
  ["字母M后面是哪个字母？", ["O", "N", "K", "L"], "N"],
  ["字母P前面是哪个字母？", ["O", "S", "R", "Q"], "O"],
  ["大写字母H的小写形式是什么？", ["m", "l", "n", "h"], "h"],
  ["小写字母d的大写形式是什么？", ["P", "B", "Q", "D"], "D"],
  ["哪个字母在字母表中排第5位？", ["F", "D", "E", "G"], "E"],
  ["哪个字母在字母表中排第10位？", ["J", "K", "H", "I"], "J"],
  ["字母O的左邻右舍是哪两个字母？", ["N和P", "M和N", "P和Q", "L和M"], "N和P"],
  ["字母S后面是哪个字母？", ["U", "T", "R", "V"], "T"],
  ["字母W前面是哪个字母？", ["X", "V", "U", "Y"], "V"],
  ["大写字母Q的小写形式是什么？", ["q", "p", "b", "d"], "q"],
  ["小写字母b的大写形式是什么？", ["R", "B", "P", "D"], "B"],
  ["哪个字母在字母表中排第15位？", ["M", "N", "P", "O"], "O"],
  ["哪个字母在字母表中排第20位？", ["T", "R", "S", "U"], "T"],
  ["字母K的左邻右舍是哪两个字母？", ["H和I", "L和M", "I和J", "J和L"], "J和L"],
  ["字母F后面是哪个字母？", ["G", "E", "D", "H"], "G"],
  ["字母X前面是哪个字母？", ["V", "Y", "W", "Z"], "W"],
  ["哪个字母在字母表中排第7位？", ["I", "H", "F", "G"], "G"],

  // ===== 问候与日常交际（约25题）=====
  ["早上见到老师应该说：", ["Good morning", "Good evening", "Good afternoon", "Good night"], "Good morning"],
  ["下午见到同学应该说：", ["Good afternoon", "Good morning", "Good evening", "Good night"], "Good afternoon"],
  ["晚上睡觉前应该说：", ["Good morning", "Good night", "Good evening", "Good afternoon"], "Good night"],
  ["别人问\"How are you?\"，你应该回答：", ["I'm fine, thank you", "How are you", "Goodbye", "Nice to meet you"], "I'm fine, thank you"],
  ["初次见面应该说：", ["How are you", "Goodbye", "Nice to meet you", "Good morning"], "Nice to meet you"],
  ["和别人告别应该说：", ["Goodbye", "Hello", "How are you", "Nice to meet you"], "Goodbye"],
  ["早上好的英语怎么说？", ["Good night", "Good afternoon", "Good evening", "Good morning"], "Good morning"],
  ["下午好的英语怎么说？", ["Good night", "Good evening", "Good morning", "Good afternoon"], "Good afternoon"],
  ["晚上好的英语怎么说？", ["Good afternoon", "Good evening", "Good night", "Good morning"], "Good evening"],
  ["晚安的英语怎么说？", ["Good evening", "Good morning", "Good night", "Good afternoon"], "Good night"],
  ["你好吗？的英语怎么说？", ["How are you", "Goodbye", "Hello", "Good morning"], "How are you"],
  ["我很好，谢谢的英语怎么说？", ["Goodbye", "I'm fine, thank you", "How are you", "Hello"], "I'm fine, thank you"],
  ["很高兴见到你的英语怎么说？", ["Hello", "Goodbye", "How are you", "Nice to meet you"], "Nice to meet you"],
  ["见到朋友时可以说：", ["Goodbye", "Good night", "Hello", "Good evening"], "Hello"],
  ["\"Thank you\"是什么意思？", ["你好", "谢谢", "再见", "对不起"], "谢谢"],
  ["\"Sorry\"是什么意思？", ["你好", "谢谢", "再见", "对不起"], "对不起"],
  ["别人说\"Thank you\"，你应该说：", ["Sorry", "You're welcome", "Goodbye", "Hello"], "You're welcome"],
  ["\"Please\"是什么意思？", ["请", "谢谢", "对不起", "再见"], "请"],
  ["想请求帮助时应该说：", ["Goodbye", "How are you", "Please help me", "Good morning"], "Please help me"],
  ["别人帮助了你，你应该说：", ["Sorry", "Goodbye", "Hello", "Thank you"], "Thank you"],
  ["早上见面打招呼说：", ["Good evening", "Good afternoon", "Good night", "Good morning"], "Good morning"],
  ["下午三点见面打招呼说：", ["Good evening", "Good night", "Good afternoon", "Good morning"], "Good afternoon"],
  ["晚上七点见面打招呼说：", ["Good afternoon", "Good evening", "Good morning", "Good night"], "Good evening"],
  ["睡觉前对爸爸妈妈说：", ["Good afternoon", "Good morning", "Good evening", "Good night"], "Good night"],
  ["\"Excuse me\"是什么意思？", ["打扰一下", "谢谢", "再见", "你好"], "打扰一下"],

  // ===== 颜色（约15题）=====
  ["红色的英语怎么说？", ["blue", "green", "yellow", "red"], "red"],
  ["蓝色的英语怎么说？", ["blue", "red", "green", "yellow"], "blue"],
  ["黄色的英语怎么说？", ["yellow", "green", "red", "blue"], "yellow"],
  ["绿色的英语怎么说？", ["blue", "red", "green", "yellow"], "green"],
  ["紫色的英语怎么说？", ["pink", "purple", "orange", "brown"], "purple"],
  ["粉色的英语怎么说？", ["pink", "brown", "orange", "purple"], "pink"],
  ["橙色的英语怎么说？", ["pink", "purple", "orange", "brown"], "orange"],
  ["棕色的英语怎么说？", ["orange", "pink", "purple", "brown"], "brown"],
  ["黑色的英语怎么说？", ["gray", "black", "white", "brown"], "black"],
  ["白色的英语怎么说？", ["gray", "brown", "black", "white"], "white"],
  ["灰色的英语怎么说？", ["black", "gray", "white", "brown"], "gray"],
  ["天空是什么颜色？", ["green", "red", "blue", "yellow"], "blue"],
  ["草地是什么颜色？", ["yellow", "blue", "red", "green"], "green"],
  ["香蕉是什么颜色？", ["green", "red", "yellow", "blue"], "yellow"],
  ["熊猫是什么颜色？", ["pink", "white and black", "orange", "brown"], "white and black"],

  // ===== 数字1-100（约25题）=====
  ["数字1的英语怎么说？", ["one", "four", "two", "three"], "one"],
  ["数字5的英语怎么说？", ["three", "five", "six", "four"], "five"],
  ["数字10的英语怎么说？", ["eight", "eleven", "ten", "nine"], "ten"],
  ["数字11的英语怎么说？", ["ten", "twelve", "thirteen", "eleven"], "eleven"],
  ["数字12的英语怎么说？", ["twelve", "eleven", "ten", "thirteen"], "twelve"],
  ["数字15的英语怎么说？", ["fifteen", "fourteen", "thirteen", "sixteen"], "fifteen"],
  ["数字20的英语怎么说？", ["forty", "twenty", "fifty", "thirty"], "twenty"],
  ["数字30的英语怎么说？", ["forty", "twenty", "fifty", "thirty"], "thirty"],
  ["数字40的英语怎么说？", ["forty", "fifty", "twenty", "thirty"], "forty"],
  ["数字50的英语怎么说？", ["twenty", "forty", "thirty", "fifty"], "fifty"],
  ["数字13的英语怎么说？", ["fourteen", "fifteen", "sixteen", "thirteen"], "thirteen"],
  ["数字14的英语怎么说？", ["fourteen", "fifteen", "thirteen", "sixteen"], "fourteen"],
  ["数字16的英语怎么说？", ["sixteen", "fifteen", "fourteen", "seventeen"], "sixteen"],
  ["数字17的英语怎么说？", ["fifteen", "sixteen", "eighteen", "seventeen"], "seventeen"],
  ["数字18的英语怎么说？", ["eighteen", "sixteen", "seventeen", "nineteen"], "eighteen"],
  ["数字19的英语怎么说？", ["eighteen", "seventeen", "twenty", "nineteen"], "nineteen"],
  ["数字60的英语怎么说？", ["eighty", "seventy", "sixty", "fifty"], "sixty"],
  ["数字70的英语怎么说？", ["sixty", "ninety", "eighty", "seventy"], "seventy"],
  ["数字80的英语怎么说？", ["one hundred", "ninety", "seventy", "eighty"], "eighty"],
  ["数字90的英语怎么说？", ["eighty", "one hundred", "ninety", "seventy"], "ninety"],
  ["数字100的英语怎么说？", ["ninety", "one hundred", "eighty", "ninety-nine"], "one hundred"],
  ["21的英语怎么说？", ["twenty-two", "twenty-three", "twenty-one", "twenty-four"], "twenty-one"],
  ["35的英语怎么说？", ["thirty-four", "thirty-six", "thirty-five", "thirty-seven"], "thirty-five"],
  ["42的英语怎么说？", ["forty-one", "forty-three", "forty-four", "forty-two"], "forty-two"],
  ["58的英语怎么说？", ["fifty-seven", "fifty-eight", "fifty-nine", "fifty-six"], "fifty-eight"],

  // ===== 身体部位（约15题）=====
  ["眼睛的英语怎么说？", ["eye", "mouth", "ear", "nose"], "eye"],
  ["耳朵的英语怎么说？", ["eye", "ear", "nose", "mouth"], "ear"],
  ["鼻子的英语怎么说？", ["ear", "nose", "mouth", "eye"], "nose"],
  ["嘴巴的英语怎么说？", ["nose", "ear", "mouth", "eye"], "mouth"],
  ["手的英语怎么说？", ["hand", "head", "arm", "foot"], "hand"],
  ["脚的英语怎么说？", ["arm", "head", "hand", "foot"], "foot"],
  ["头的英语怎么说？", ["foot", "head", "hand", "arm"], "head"],
  ["手臂的英语怎么说？", ["foot", "arm", "hand", "head"], "arm"],
  ["腿的英语怎么说？", ["leg", "foot", "hand", "arm"], "leg"],
  ["手指的英语怎么说？", ["toe", "shoulder", "knee", "finger"], "finger"],
  ["脚趾的英语怎么说？", ["finger", "knee", "shoulder", "toe"], "toe"],
  ["肩膀的英语怎么说？", ["knee", "shoulder", "toe", "finger"], "shoulder"],
  ["膝盖的英语怎么说？", ["shoulder", "toe", "finger", "knee"], "knee"],
  ["脸的英语怎么说？", ["arm", "head", "face", "hand"], "face"],
  ["头发的英语怎么说？", ["eye", "hair", "face", "head"], "hair"],

  // ===== 动物（约20题）=====
  ["狗的英语怎么说？", ["cat", "dog", "bird", "fish"], "dog"],
  ["猫的英语怎么说？", ["cat", "fish", "dog", "bird"], "cat"],
  ["鸟的英语怎么说？", ["dog", "bird", "cat", "fish"], "bird"],
  ["鱼的英语怎么说？", ["bird", "dog", "cat", "fish"], "fish"],
  ["鸭子的英语怎么说？", ["cow", "duck", "sheep", "pig"], "duck"],
  ["猪的英语怎么说？", ["duck", "cow", "sheep", "pig"], "pig"],
  ["奶牛的英语怎么说？", ["cow", "sheep", "duck", "pig"], "cow"],
  ["绵羊的英语怎么说？", ["sheep", "pig", "cow", "duck"], "sheep"],
  ["马的英语怎么说？", ["horse", "monkey", "panda", "bear"], "horse"],
  ["熊的英语怎么说？", ["monkey", "horse", "panda", "bear"], "bear"],
  ["猴子的英语怎么说？", ["panda", "bear", "horse", "monkey"], "monkey"],
  ["熊猫的英语怎么说？", ["horse", "monkey", "bear", "panda"], "panda"],
  ["兔子的英语怎么说？", ["lion", "tiger", "rabbit", "elephant"], "rabbit"],
  ["老虎的英语怎么说？", ["rabbit", "tiger", "elephant", "lion"], "tiger"],
  ["狮子的英语怎么说？", ["lion", "rabbit", "elephant", "tiger"], "lion"],
  ["大象的英语怎么说？", ["tiger", "elephant", "lion", "rabbit"], "elephant"],
  ["鸡的英语怎么说？", ["duck", "chicken", "goose", "bird"], "chicken"],
  ["蛇的英语怎么说？", ["frog", "snake", "fish", "turtle"], "snake"],
  ["青蛙的英语怎么说？", ["frog", "fish", "turtle", "snake"], "frog"],
  ["乌龟的英语怎么说？", ["turtle", "fish", "frog", "snake"], "turtle"],

  // ===== 食物与饮料（约20题）=====
  ["米饭的英语怎么说？", ["noodle", "rice", "bread", "cake"], "rice"],
  ["面条的英语怎么说？", ["cake", "rice", "noodle", "bread"], "noodle"],
  ["面包的英语怎么说？", ["cake", "bread", "noodle", "rice"], "bread"],
  ["蛋糕的英语怎么说？", ["noodle", "rice", "cake", "bread"], "cake"],
  ["鱼的英语（食物）怎么说？", ["fish", "pork", "beef", "chicken"], "fish"],
  ["鸡肉的英语怎么说？", ["pork", "fish", "beef", "chicken"], "chicken"],
  ["牛肉的英语怎么说？", ["pork", "fish", "chicken", "beef"], "beef"],
  ["猪肉的英语怎么说？", ["chicken", "pork", "fish", "beef"], "pork"],
  ["果汁的英语怎么说？", ["milk", "juice", "water", "tea"], "juice"],
  ["牛奶的英语怎么说？", ["water", "tea", "juice", "milk"], "milk"],
  ["水的英语怎么说？", ["tea", "water", "milk", "juice"], "water"],
  ["茶的英语怎么说？", ["milk", "tea", "juice", "water"], "tea"],
  ["苹果的英语怎么说？", ["orange", "pear", "banana", "apple"], "apple"],
  ["香蕉的英语怎么说？", ["banana", "pear", "orange", "apple"], "banana"],
  ["橙子的英语怎么说？", ["apple", "pear", "banana", "orange"], "orange"],
  ["梨的英语怎么说？", ["pear", "apple", "banana", "orange"], "pear"],
  ["鸡蛋的英语怎么说？", ["cake", "egg", "apple", "bread"], "egg"],
  ["蔬菜的英语怎么说？", ["vegetable", "rice", "meat", "fruit"], "vegetable"],
  ["水果的英语怎么说？", ["meat", "vegetable", "fruit", "rice"], "fruit"],
  ["冰淇淋的英语怎么说？", ["bread", "ice cream", "cookie", "cake"], "ice cream"],

  // ===== 衣服（约15题）=====
  ["衬衫的英语怎么说？", ["skirt", "dress", "shirt", "T-shirt"], "shirt"],
  ["T恤的英语怎么说？", ["shirt", "dress", "skirt", "T-shirt"], "T-shirt"],
  ["裙子的英语怎么说？", ["shirt", "skirt", "T-shirt", "dress"], "skirt"],
  ["连衣裙的英语怎么说？", ["dress", "shirt", "skirt", "T-shirt"], "dress"],
  ["帽子的英语怎么说？", ["hat", "socks", "shoes", "cap"], "hat"],
  ["鞋子的英语怎么说？", ["socks", "hat", "shoes", "cap"], "shoes"],
  ["袜子的英语怎么说？", ["cap", "shoes", "hat", "socks"], "socks"],
  ["裤子的英语怎么说？", ["jacket", "coat", "pants", "shorts"], "pants"],
  ["短裤的英语怎么说？", ["jacket", "coat", "shorts", "pants"], "shorts"],
  ["外套的英语怎么说？", ["jacket", "coat", "shorts", "pants"], "coat"],
  ["夹克的英语怎么说？", ["shorts", "jacket", "pants", "coat"], "jacket"],
  ["毛衣的英语怎么说？", ["shirt", "sweater", "coat", "jacket"], "sweater"],
  ["手套的英语怎么说？", ["shoes", "hat", "gloves", "socks"], "gloves"],
  ["围巾的英语怎么说？", ["coat", "scarf", "hat", "gloves"], "scarf"],
  ["雨衣的英语怎么说？", ["sweater", "jacket", "raincoat", "coat"], "raincoat"],

  // ===== 交通工具（约15题）=====
  ["小汽车的英语怎么说？", ["car", "train", "bike", "bus"], "car"],
  ["公共汽车的英语怎么说？", ["bike", "bus", "car", "train"], "bus"],
  ["自行车的英语怎么说？", ["bike", "train", "bus", "car"], "bike"],
  ["火车的英语怎么说？", ["bike", "car", "train", "bus"], "train"],
  ["飞机的英语怎么说？", ["plane", "boat", "car", "ship"], "plane"],
  ["轮船的英语怎么说？", ["car", "plane", "ship", "boat"], "ship"],
  ["小船的英语怎么说？", ["car", "plane", "ship", "boat"], "boat"],
  ["出租车的英语怎么说？", ["taxi", "bus", "train", "car"], "taxi"],
  ["地铁的英语怎么说？", ["bus", "train", "taxi", "subway"], "subway"],
  ["摩托车的英语怎么说？", ["bike", "car", "bus", "motorcycle"], "motorcycle"],
  ["直升机/直升飞机的英语怎么说？", ["train", "ship", "plane", "helicopter"], "helicopter"],
  ["卡车/货车的英语怎么说？", ["bus", "truck", "taxi", "car"], "truck"],
  ["警车的英语怎么说？", ["bus", "taxi", "police car", "truck"], "police car"],
  ["救护车的英语怎么说？", ["fire truck", "bus", "ambulance", "police car"], "ambulance"],
  ["消防车的英语怎么说？", ["ambulance", "police car", "fire truck", "bus"], "fire truck"],

  // ===== 星期与月份（约15题）=====
  ["星期一的英语怎么说？", ["Thursday", "Wednesday", "Tuesday", "Monday"], "Monday"],
  ["星期二的英语怎么说？", ["Tuesday", "Wednesday", "Monday", "Thursday"], "Tuesday"],
  ["星期三的英语怎么说？", ["Wednesday", "Thursday", "Tuesday", "Monday"], "Wednesday"],
  ["星期四的英语怎么说？", ["Thursday", "Wednesday", "Tuesday", "Monday"], "Thursday"],
  ["星期五的英语怎么说？", ["Saturday", "Monday", "Friday", "Sunday"], "Friday"],
  ["星期六的英语怎么说？", ["Sunday", "Monday", "Friday", "Saturday"], "Saturday"],
  ["星期日的英语怎么说？", ["Monday", "Sunday", "Saturday", "Friday"], "Sunday"],
  ["一月的英语怎么说？", ["April", "February", "March", "January"], "January"],
  ["二月的英语怎么说？", ["January", "February", "March", "April"], "February"],
  ["三月的英语怎么说？", ["March", "January", "April", "February"], "March"],
  ["四月的英语怎么说？", ["February", "January", "April", "March"], "April"],
  ["五月的英语怎么说？", ["June", "May", "August", "July"], "May"],
  ["六月的英语怎么说？", ["July", "August", "May", "June"], "June"],
  ["七月的英语怎么说？", ["May", "June", "July", "August"], "July"],
  ["八月的英语怎么说？", ["July", "August", "May", "June"], "August"],

  // ===== 简单句型（约15题）=====
  ["\"我喜欢苹果\"用英语怎么说？", ["I like apples", "I have apples", "This is an apple", "I see apples"], "I like apples"],
  ["\"我有一只猫\"用英语怎么说？", ["I like a cat", "I have a cat", "This is a cat", "I see a cat"], "I have a cat"],
  ["\"这是一本书\"用英语怎么说？", ["I like a book", "I have a book", "This is a book", "I see a book"], "This is a book"],
  ["\"这是什么颜色？\"用英语怎么说？", ["What colour is it", "What is it", "How many", "Where is it"], "What colour is it"],
  ["\"有多少个苹果？\"用英语怎么说？", ["What colour", "How many apples", "What is it", "Where is it"], "How many apples"],
  ["\"它是红色的\"用英语怎么说？", ["It's red", "It's blue", "It's green", "It's yellow"], "It's red"],
  ["\"我喜欢狗\"用英语怎么说？", ["I like dogs", "I have dogs", "This is a dog", "I see dogs"], "I like dogs"],
  ["\"我有一本书\"用英语怎么说？", ["I like a book", "I have a book", "This is a book", "I see a book"], "I have a book"],
  ["\"这是一只猫\"用英语怎么说？", ["I like a cat", "I have a cat", "This is a cat", "I see a cat"], "This is a cat"],
  ["\"它是蓝色的\"用英语怎么说？", ["It's red", "It's blue", "It's green", "It's yellow"], "It's blue"],
  ["\"我喜欢香蕉\"用英语怎么说？", ["I like bananas", "I have bananas", "This is a banana", "I see bananas"], "I like bananas"],
  ["\"我有两只手\"用英语怎么说？", ["I like two hands", "I have two hands", "This is a hand", "I see two hands"], "I have two hands"],
  ["\"这是什么？\"用英语怎么说？", ["What colour", "What is this", "How many", "Where is it"], "What is this"],
  ["\"它在哪儿？\"用英语怎么说？", ["What colour", "What is this", "How many", "Where is it"], "Where is it"],
  ["\"它是绿色的\"用英语怎么说？", ["It's red", "It's blue", "It's green", "It's yellow"], "It's green"],

  // ===== 补充题目（5题）=====
  ["\"再见\"的英语怎么说？", ["Goodbye", "Hello", "Sorry", "Thank you"], "Goodbye"],
  ["九月的英语怎么说？", ["November", "September", "October", "December"], "September"],
  ["十月的英语怎么说？", ["November", "December", "September", "October"], "October"],
  ["十一月的英语怎么说？", ["September", "December", "November", "October"], "November"],
  ["十二月的英语怎么说？", ["October", "December", "November", "September"], "December"],
];
