// 初一英语题库 - 人教版七年级（Go for it!）
// 共200题

final List<List<dynamic>> grade7EnglishBank = [
  ["英语字母表中共有多少个字母？", ["24个", "25个", "26个", "27个"], "26个"],
  ["以下哪个是元音字母？", ["B", "C", "A", "D"], "A"],
  ["以下哪个是辅音字母？", ["E", "I", "M", "O"], "M"],
  ["字母表中第五个字母是什么？", ["D", "E", "F", "G"], "E"],
  ["以下哪组都是元音字母？", ["A,E,I,O", "B,C,D,E", "A,B,C,D", "E,F,G,H"], "A,E,I,O"],
  ["字母N的小写形式是？", ["n", "m", "h", "u"], "n"],
  ["以下哪个字母含有/ei/音？", ["B", "A", "C", "D"], "A"],
  ["字母H的发音首音素是？", ["/ei/", "/ai/", "/eitʃ/", "/iː/"], "/eitʃ/"],
  ["英语字母表中最后一个字母是？", ["X", "Y", "Z", "W"], "Z"],
  ["以下哪个字母是半元音？", ["L", "W", "M", "N"], "W"],
  ["字母J和哪个字母发音首音素相同？", ["G", "K", "H", "J"], "G"],
  ["小写字母b和d的主要区别是？", ["形状相同", "肚子的方向不同", "高度不同", "没有区别"], "肚子的方向不同"],
  ["以下哪个字母名称含有/iː/音？", ["B", "C", "D", "E"], "E"],
  ["字母Q经常和哪个字母一起出现？", ["A", "U", "O", "I"], "U"],
  ["26个字母中有多少个辅音字母？", ["20个", "21个", "22个", "19个"], "21个"],
  ["Whats this? Its a _____.", ["book", "books", "booking", "booked"], "book"],
  ["My father is a _____.", ["teacher", "doctor", "student", "driver"], "doctor"],
  ["There are many _____ in the zoo.", ["animal", "animals", "animals", "animals"], "animals"],
  ["I like eating _____.", ["apple", "apples", "apples", "apples"], "apples"],
  ["My sister has long _____.", ["hair", "hairs", "hairs", "hairs"], "hair"],
  ["There is some _____ on the table.", ["bread", "breads", "breads", "breads"], "bread"],
  ["My birthday is in _____.", ["May", "may", "MAY", "Mays"], "May"],
  ["I have two _____.", ["foot", "feet", "feet", "feet"], "feet"],
  ["The _____ are flying.", ["child", "childs", "children", "childrens"], "children"],
  ["I brush my _____ every day.", ["tooth", "tooths", "teeth", "teeths"], "teeth"],
  ["I _____ to school every day.", ["go", "goes", "going", "went"], "go"],
  ["My mother _____ breakfast.", ["cook", "cooks", "cooking", "cooked"], "cooks"],
  ["He _____ his homework.", ["do", "does", "doing", "done"], "does"],
  ["They _____ English every morning.", ["study", "studies", "studying", "studied"], "study"],
  ["She _____ to music.", ["listen", "listens", "listening", "listened"], "listens"],
  ["My father _____ a car.", ["have", "has", "having", "had"], "has"],
  ["We _____ basketball.", ["play", "plays", "playing", "played"], "play"],
  ["Tom _____ up at 6:00.", ["get", "gets", "getting", "got"], "gets"],
  ["The dog _____ fast.", ["run", "runs", "running", "ran"], "runs"],
  ["My sister _____ TV.", ["watch", "watches", "watching", "watched"], "watches"],
  ["The apple is _____.", ["red", "a red", "reds", "reds"], "red"],
  ["I feel very _____ today.", ["happy", "happily", "happiness", "happier"], "happy"],
  ["The boy is _____.", ["kind", "kinder", "kindly", "kinds"], "kind"],
  ["This book is very _____.", ["interest", "interesting", "interested", "interests"], "interesting"],
  ["The elephant is _____.", ["big", "bigger", "biggest", "bigs"], "big"],
  ["Im _____ in English.", ["interest", "interesting", "interested", "interests"], "interested"],
  ["The weather is _____ today.", ["good", "well", "better", "best"], "good"],
  ["She looks _____.", ["beautiful", "beautifully", "beauty", "beauties"], "beautiful"],
  ["The story is very _____.", ["bore", "boring", "bored", "bores"], "boring"],
  ["Im _____ in this movie.", ["bore", "boring", "bored", "bores"], "bored"],
  ["I _____ get up early.", ["usual", "usually", "unusual", "unusually"], "usually"],
  ["She speaks English _____.", ["good", "well", "nice", "fine"], "well"],
  ["I go to school _____ bus.", ["in", "on", "by", "at"], "by"],
  ["The book is _____ the desk.", ["in", "on", "at", "under"], "on"],
  ["_____ is my teacher.", ["He", "His", "Him", "Her"], "He"],
  ["This is my book. _____ is yours.", ["Your", "Yours", "You", "Yours"], "Yours"],
  ["Give _____ the pen.", ["my", "me", "I", "mine"], "me"],
  ["There are _____ days in a week.", ["five", "six", "seven", "eight"], "seven"],
  ["September is the _____ month.", ["eighth", "ninth", "nine", "nineth"], "ninth"],
  ["My birthday is October _____.", ["five", "fifth", "fiveth", "fivth"], "fifth"],
  ["I _____ a student.", ["am", "is", "are", "be"], "am"],
  ["She _____ from China.", ["am", "is", "are", "be"], "is"],
  ["They _____ friends.", ["am", "is", "are", "be"], "are"],
  ["He _____ tall.", ["am", "is", "are", "be"], "is"],
  ["My parents _____ teachers.", ["am", "is", "are", "be"], "are"],
  ["There _____ a book.", ["am", "is", "are", "be"], "is"],
  ["There _____ some water.", ["am", "is", "are", "be"], "is"],
  ["There _____ many apples.", ["am", "is", "are", "be"], "are"],
  ["_____ you a student?", ["Am", "Is", "Are", "Be"], "Are"],
  ["Where _____ she from?", ["am", "is", "are", "be"], "is"],
  ["My father _____ to work.", ["go", "goes", "going", "went"], "goes"],
  ["We _____ English every day.", ["learn", "learns", "learning", "learned"], "learn"],
  ["_____ she like music?", ["Do", "Does", "Is", "Are"], "Does"],
  ["Tom _____ like swimming.", ["dont", "doesnt", "isnt", "arent"], "doesnt"],
  ["They often _____ TV.", ["watch", "watches", "watching", "watched"], "watch"],
  ["My mother sometimes _____ shopping.", ["go", "goes", "going", "went"], "goes"],
  ["_____ your brother play football?", ["Do", "Does", "Is", "Are"], "Does"],
  ["She _____ breakfast at 7:00.", ["have", "has", "having", "had"], "has"],
  ["We _____ to music.", ["listen", "listens", "listening", "listened"], "listen"],
  ["My grandparents _____ in Beijing.", ["live", "lives", "living", "lived"], "live"],
  ["I have two _____.", ["pen", "pens", "pens", "pens"], "pens"],
  ["There are five _____.", ["box", "boxs", "boxes", "boxs"], "boxes"],
  ["The _____ are playing.", ["baby", "babys", "babies", "babys"], "babies"],
  ["I can see three _____.", ["bird", "birds", "birds", "birds"], "birds"],
  ["My uncle has two _____.", ["child", "childs", "children", "childrens"], "children"],
  ["There are many _____.", ["book", "books", "books", "books"], "books"],
  ["I like _____ very much.", ["tomato", "tomatos", "tomatoes", "tomatos"], "tomatoes"],
  ["How many _____ do you have?", ["knife", "knifes", "knives", "knifes"], "knives"],
  ["There are some _____.", ["photo", "photos", "photoes", "photos"], "photos"],
  ["These _____ are beautiful.", ["woman", "womans", "women", "womens"], "women"],
  ["This is _____ apple.", ["a", "an", "the", "/"], "an"],
  ["He is _____ honest boy.", ["a", "an", "the", "/"], "an"],
  ["There is _____ u in use.", ["a", "an", "the", "/"], "a"],
  ["_____ sun rises in the east.", ["A", "An", "The", "/"], "The"],
  ["I have _____ orange.", ["a", "an", "the", "/"], "an"],
  ["She is _____ university student.", ["a", "an", "the", "/"], "a"],
  ["_____ moon goes around the earth.", ["A", "An", "The", "/"], "The"],
  ["What _____ interesting book!", ["a", "an", "the", "/"], "an"],
  ["My father is _____ engineer.", ["a", "an", "the", "/"], "an"],
  ["There is _____ elephant.", ["a", "an", "the", "/"], "an"],
  ["There _____ a pen and two pencils.", ["is", "are", "has", "have"], "is"],
  ["There _____ some bread.", ["is", "are", "has", "have"], "is"],
  ["_____ there any students?", ["Is", "Are", "Has", "Have"], "Are"],
  ["There _____ a match tomorrow.", ["is", "are", "will be", "has"], "will be"],
  ["There _____ no time.", ["is", "are", "has", "have"], "is"],
  ["_____ the door.", ["Open", "Opens", "Opening", "To open"], "Open"],
  ["_____ be late.", ["Dont", "Doesnt", "Isnt", "Arent"], "Dont"],
  ["Lets _____ to school.", ["go", "goes", "going", "to go"], "go"],
  ["_____ is your father? A teacher.", ["What", "Who", "How", "Where"], "What"],
  ["_____ do you go to school? By bus.", ["What", "Who", "How", "Where"], "How"],
  ["She is a teacher. She _____ a teacher.", ["isnt", "doesnt", "arent", "not"], "isnt"],
  ["They are students. They _____ students.", ["isnt", "arent", "dont", "doesnt"], "arent"],
  ["I have a pen. I _____ a pen.", ["dont have", "doesnt have", "havent", "not have"], "dont have"],
  ["He likes music. He _____ music.", ["dont like", "doesnt like", "not like", "isnt like"], "doesnt like"],
  ["We go to school. We _____ to school.", ["dont go", "doesnt go", "not go", "arent go"], "dont go"],
  ["There is some water. There _____ water.", ["isnt some", "isnt any", "arent any", "not any"], "isnt any"],
  ["She can swim. She _____ swim.", ["cant", "doesnt", "isnt", "not"], "cant"],
  ["My brother plays football. My brother _____ football.", ["dont play", "doesnt play", "not play", "isnt play"], "doesnt play"],
  ["They have lunch. They _____ lunch.", ["dont have", "doesnt have", "havent", "not have"], "dont have"],
  ["He is reading. He _____ reading.", ["isnt", "doesnt", "dont", "not"], "isnt"],
  ["She is a student. _____ she a student?", ["Is", "Does", "Do", "Are"], "Is"],
  ["They are from China. _____ they from China?", ["Is", "Does", "Do", "Are"], "Are"],
  ["He likes music. _____ he like music?", ["Does", "Do", "Is", "Does"], "Does"],
  ["They play basketball. _____ they play basketball?", ["Do", "Does", "Are", "Do"], "Do"],
  ["There is some water. _____ there any water?", ["Is", "Are", "Is", "Are"], "Is"],
  ["She can swim. _____ she swim?", ["Can", "Does", "Is", "Do"], "Can"],
  ["I have a pen. _____ you have a pen?", ["Do", "Does", "Are", "Do"], "Do"],
  ["He goes to school. _____ he go to school?", ["Does", "Do", "Is", "Does"], "Does"],
  ["There are some books. _____ there any books?", ["Are", "Is", "Are", "Is"], "Are"],
  ["My sister likes cats. _____ your sister like cats?", ["Does", "Do", "Is", "Does"], "Does"],
  ["My name is Tom. _____ is your name?", ["What", "Who", "How", "Where"], "What"],
  ["She is from America. _____ is she from?", ["What", "Who", "How", "Where"], "Where"],
  ["Im fine. _____ are you?", ["What", "Who", "How", "Where"], "How"],
  ["He is my brother. _____ is he?", ["What", "Who", "How", "Where"], "Who"],
  ["Its seven oclock. _____ is it?", ["What time", "What day", "What color", "What class"], "What time"],
  ["Good morning! _____", ["Good morning!", "Good afternoon!", "Good evening!", "Good night!"], "Good morning!"],
  ["How are you? _____", ["Im fine, thanks.", "How are you?", "Fine, thank you.", "Good."], "Im fine, thanks."],
  ["Nice to meet you. _____", ["Nice to meet you, too.", "Thank you.", "Im fine.", "Goodbye."], "Nice to meet you, too."],
  ["Goodbye! _____", ["Goodbye!", "Hello!", "Hi!", "Good morning!"], "Goodbye!"],
  ["How do you do? _____", ["How do you do?", "Im fine.", "Thank you.", "Nice to meet you."], "How do you do?"],
  ["Whats your name? _____", ["My name is Tom.", "Im Tom.", "This is Tom.", "Fine, thanks."], "My name is Tom."],
  ["_____ Im from China.", ["Where are you from?", "Whats your name?", "How are you?", "How old are you?"], "Where are you from?"],
  ["How old are you? _____", ["Im twelve.", "Im fine.", "Im from China.", "My name is Tom."], "Im twelve."],
  ["This is my friend. _____", ["Nice to meet you.", "How are you?", "Im fine.", "Thank you."], "Nice to meet you."],
  ["What class are you in? _____", ["Im in Class 1.", "Im in Grade 1.", "Im twelve.", "Im from China."], "Im in Class 1."],
  ["Thank you! _____", ["Youre welcome.", "Thank you.", "Thats right.", "All right."], "Youre welcome."],
  ["Thanks for your help. _____", ["Youre welcome.", "Thats right.", "All right.", "OK."], "Youre welcome."],
  ["_____ Youre welcome.", ["Thank you.", "Sorry.", "Excuse me.", "Goodbye."], "Thank you."],
  ["Thanks a lot! _____", ["Thats all right.", "Thats right.", "All right.", "Thats OK."], "Thats all right."],
  ["Its very kind of you. _____", ["Youre welcome.", "Dont say that.", "No, thanks.", "Yes, please."], "Youre welcome."],
  ["Im sorry. _____", ["Thats all right.", "Thank you.", "Thats right.", "All right."], "Thats all right."],
  ["Sorry, Im late. _____", ["Thats OK.", "Thank you.", "Thats right.", "No, thanks."], "Thats OK."],
  ["_____ Thats OK.", ["Sorry.", "Thank you.", "Excuse me.", "Hello."], "Sorry."],
  ["Excuse me. _____", ["Yes?", "No?", "OK?", "Sorry?"], "Yes?"],
  ["Im sorry I broke your pen. _____", ["It doesnt matter.", "Thats right.", "All right.", "No problem."], "It doesnt matter."],
  ["Can I use your pen? _____", ["Sure. Here you are.", "No, thanks.", "Yes, I can.", "Youre welcome."], "Sure. Here you are."],
  ["May I come in? _____", ["Come in, please.", "Yes, you may.", "No, you may not.", "Thats all right."], "Come in, please."],
  ["Could you help me? _____", ["Sure.", "No, I couldnt.", "Yes, I could.", "Youre welcome."], "Sure."],
  ["_____ Sure. Here you are.", ["Can I use your ruler?", "Thank you.", "Sorry.", "Excuse me."], "Can I use your ruler?"],
  ["Would you like some tea? _____", ["Yes, please.", "No, please.", "Yes, I would.", "No, I wouldnt."], "Yes, please."],
  ["May I speak to Tom? _____", ["This is Tom speaking.", "Im Tom.", "My name is Tom.", "That is Tom."], "This is Tom speaking."],
  ["Is that Tom? _____", ["Yes, this is Tom speaking.", "Yes, Im Tom.", "Yes, that is Tom.", "Yes, you are Tom."], "Yes, this is Tom speaking."],
  ["Whos that? _____", ["This is Mary.", "Im Mary.", "That is Mary.", "My name is Mary."], "This is Mary."],
  ["Can I take a message? _____", ["Yes, please.", "No, thanks.", "Yes, I can.", "Thats right."], "Yes, please."],
  ["Hello! 88654321. _____", ["Hello! Is that Tom?", "Im Tom.", "My name is Tom.", "Who are you?"], "Hello! Is that Tom?"],
  ["Tom is 12 years old. He is from America. He is in Class 1. His father is a teacher. His mother is a doctor. He has a sister Mary, she is 10. How old is Tom?", ["10", "11", "12", "13"], "12"],
  ["What class is Tom in?", ["Class 2", "Class 1", "Class 3", "Class 4"], "Class 1"],
  ["Where is Tom from?", ["China", "England", "America", "Japan"], "America"],
  ["What is Toms father?", ["A doctor", "A teacher", "A driver", "A worker"], "A teacher"],
  ["How old is Mary?", ["10", "11", "12", "13"], "10"],
  ["Li Hua is 13. He is Chinese. He likes basketball. His friend Tom is from England. Tom likes football. What is the boys name?", ["Tom", "Li Hua", "Wang", "Zhang"], "Li Hua"],
  ["How old is Li Hua?", ["11", "12", "13", "14"], "13"],
  ["What does Li Hua like?", ["Football", "Basketball", "Swimming", "Running"], "Basketball"],
  ["Where is Tom from?", ["China", "America", "England", "Japan"], "England"],
  ["What does Tom like?", ["Football", "Basketball", "Swimming", "Running"], "Football"],
  ["My room is small but nice. There is a bed next to the window. A desk is under the window. A computer is on the desk. I like reading books. How is the room?", ["Big", "Small but nice", "Old", "Bad"], "Small but nice"],
  ["What is next to the window?", ["The desk", "The bed", "The chair", "The computer"], "The bed"],
  ["Where is the desk?", ["Next to the bed", "Under the window", "On the bed", "By the door"], "Under the window"],
  ["What is on the desk?", ["Books", "A computer", "A bag", "A pen"], "A computer"],
  ["What does the writer like?", ["Games", "Reading", "TV", "Sleeping"], "Reading"],
  ["Alice is 11. She is English. Her brother Tom is 14. Her father is a doctor. Her mother is a teacher. Alice likes singing. What is the girls name?", ["Tom", "Alice", "Mary", "Lucy"], "Alice"],
  ["How old is Alice?", ["10", "11", "12", "13"], "11"],
  ["How old is Tom?", ["11", "12", "13", "14"], "14"],
  ["What is Alices father?", ["A teacher", "A doctor", "A driver", "A worker"], "A doctor"],
  ["What does Alice like?", ["Football", "Singing", "Reading", "Swimming"], "Singing"],
  ["圣诞节在哪个月？", ["十月", "十一月", "十二月", "一月"], "十二月"],
  ["美国国庆节是？", ["July 4th", "July 14th", "August 4th", "June 4th"], "July 4th"],
  ["Thank you的回答是？", ["Youre welcome", "Thank you", "Good", "OK"], "Youre welcome"],
  ["见面问候语是？", ["Have you eaten?", "Where are you going?", "How are you?", "Whats your name?"], "How are you?"],
  ["万圣节是哪天？", ["October 31st", "November 1st", "October 30th", "December 25th"], "October 31st"],
  ["Hello可用于？", ["只在早上", "只在下午", "任何时间", "只在晚上"], "任何时间"],
  ["母亲节在哪月？", ["三月", "四月", "五月", "六月"], "五月"],
  ["收到礼物应该？", ["马上打开", "回家再打开", "不要打开", "还给对方"], "马上打开"],
  ["复活节象征是？", ["圣诞树", "彩蛋", "南瓜", "火鸡"], "彩蛋"],
  ["Merry Christmas意思是？", ["新年快乐", "生日快乐", "圣诞快乐", "复活节快乐"], "圣诞快乐"],
  ["My favorite _____ is blue.", ["color", "sport", "food", "subject"], "color"],
  ["I play _____ with friends.", ["piano", "the piano", "a piano", "pianos"], "the piano"],
  ["There are twelve _____ in a year.", ["days", "weeks", "months", "seasons"], "months"],
  ["My father often _____ newspapers.", ["read", "reads", "reading", "to read"], "reads"],
  ["I have breakfast _____ 7:00.", ["in", "on", "at", "for"], "at"],
  ["The book is _____.", ["interesting", "interested", "interest", "interests"], "interesting"],
  ["My mother is good at _____.", ["cook", "cooking", "cooks", "to cook"], "cooking"],
  ["I help my mother _____ housework.", ["do", "doing", "does", "to doing"], "do"],
  ["Tom is _____ at English.", ["good", "better", "best", "well"], "good"],
  ["Whats your _____ subject?", ["like", "favorite", "love", "good"], "favorite"],
];